// Code generated by ent, DO NOT EDIT.

package requestauditreservation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the requestauditreservation type in the database.
	Label = "request_audit_reservation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLogicalKey holds the string denoting the logical_key field in the database.
	FieldLogicalKey = "logical_key"
	// FieldRouteFamily holds the string denoting the route_family field in the database.
	FieldRouteFamily = "route_family"
	// FieldForced holds the string denoting the forced field in the database.
	FieldForced = "forced"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldCaptureCompleteness holds the string denoting the capture_completeness field in the database.
	FieldCaptureCompleteness = "capture_completeness"
	// FieldCaptureReason holds the string denoting the capture_reason field in the database.
	FieldCaptureReason = "capture_reason"
	// FieldSendStartedAt holds the string denoting the send_started_at field in the database.
	FieldSendStartedAt = "send_started_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUsageLog holds the string denoting the usage_log edge name in mutations.
	EdgeUsageLog = "usage_log"
	// Table holds the table name of the requestauditreservation in the database.
	Table = "request_audit_reservations"
	// UsageLogTable is the table that holds the usage_log relation/edge.
	UsageLogTable = "request_audit_reservations"
	// UsageLogInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogInverseTable = "usage_logs"
	// UsageLogColumn is the table column denoting the usage_log relation/edge.
	UsageLogColumn = "usage_log_id"
)

// Columns holds all SQL columns for requestauditreservation fields.
var Columns = []string{
	FieldID,
	FieldLogicalKey,
	FieldRouteFamily,
	FieldForced,
	FieldHeaders,
	FieldAttempts,
	FieldUsageLogID,
	FieldCaptureCompleteness,
	FieldCaptureReason,
	FieldSendStartedAt,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LogicalKeyValidator is a validator for the "logical_key" field. It is called by the builders before save.
	LogicalKeyValidator func(string) error
	// RouteFamilyValidator is a validator for the "route_family" field. It is called by the builders before save.
	RouteFamilyValidator func(string) error
	// DefaultForced holds the default value on creation for the "forced" field.
	DefaultForced bool
	// DefaultHeaders holds the default value on creation for the "headers" field.
	DefaultHeaders map[string]interface{}
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts []map[string]interface{}
	// DefaultCaptureCompleteness holds the default value on creation for the "capture_completeness" field.
	DefaultCaptureCompleteness string
	// DefaultCaptureReason holds the default value on creation for the "capture_reason" field.
	DefaultCaptureReason string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RequestAuditReservation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLogicalKey orders the results by the logical_key field.
func ByLogicalKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogicalKey, opts...).ToFunc()
}

// ByRouteFamily orders the results by the route_family field.
func ByRouteFamily(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteFamily, opts...).ToFunc()
}

// ByForced orders the results by the forced field.
func ByForced(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForced, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByCaptureCompleteness orders the results by the capture_completeness field.
func ByCaptureCompleteness(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaptureCompleteness, opts...).ToFunc()
}

// ByCaptureReason orders the results by the capture_reason field.
func ByCaptureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaptureReason, opts...).ToFunc()
}

// BySendStartedAt orders the results by the send_started_at field.
func BySendStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSendStartedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUsageLogField orders the results by usage_log field.
func ByUsageLogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogStep(), sql.OrderByField(field, opts...))
	}
}
func newUsageLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
	)
}
