// Code generated by ent, DO NOT EDIT.

package requestauditreservation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldID, id))
}

// LogicalKey applies equality check predicate on the "logical_key" field. It's identical to LogicalKeyEQ.
func LogicalKey(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldLogicalKey, v))
}

// RouteFamily applies equality check predicate on the "route_family" field. It's identical to RouteFamilyEQ.
func RouteFamily(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldRouteFamily, v))
}

// Forced applies equality check predicate on the "forced" field. It's identical to ForcedEQ.
func Forced(v bool) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldForced, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldUsageLogID, v))
}

// CaptureCompleteness applies equality check predicate on the "capture_completeness" field. It's identical to CaptureCompletenessEQ.
func CaptureCompleteness(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldCaptureCompleteness, v))
}

// CaptureReason applies equality check predicate on the "capture_reason" field. It's identical to CaptureReasonEQ.
func CaptureReason(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldCaptureReason, v))
}

// SendStartedAt applies equality check predicate on the "send_started_at" field. It's identical to SendStartedAtEQ.
func SendStartedAt(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldSendStartedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldUpdatedAt, v))
}

// LogicalKeyEQ applies the EQ predicate on the "logical_key" field.
func LogicalKeyEQ(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldLogicalKey, v))
}

// LogicalKeyNEQ applies the NEQ predicate on the "logical_key" field.
func LogicalKeyNEQ(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldLogicalKey, v))
}

// LogicalKeyIn applies the In predicate on the "logical_key" field.
func LogicalKeyIn(vs ...string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldLogicalKey, vs...))
}

// LogicalKeyNotIn applies the NotIn predicate on the "logical_key" field.
func LogicalKeyNotIn(vs ...string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldLogicalKey, vs...))
}

// LogicalKeyGT applies the GT predicate on the "logical_key" field.
func LogicalKeyGT(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldLogicalKey, v))
}

// LogicalKeyGTE applies the GTE predicate on the "logical_key" field.
func LogicalKeyGTE(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldLogicalKey, v))
}

// LogicalKeyLT applies the LT predicate on the "logical_key" field.
func LogicalKeyLT(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldLogicalKey, v))
}

// LogicalKeyLTE applies the LTE predicate on the "logical_key" field.
func LogicalKeyLTE(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldLogicalKey, v))
}

// LogicalKeyContains applies the Contains predicate on the "logical_key" field.
func LogicalKeyContains(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldContains(FieldLogicalKey, v))
}

// LogicalKeyHasPrefix applies the HasPrefix predicate on the "logical_key" field.
func LogicalKeyHasPrefix(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldHasPrefix(FieldLogicalKey, v))
}

// LogicalKeyHasSuffix applies the HasSuffix predicate on the "logical_key" field.
func LogicalKeyHasSuffix(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldHasSuffix(FieldLogicalKey, v))
}

// LogicalKeyEqualFold applies the EqualFold predicate on the "logical_key" field.
func LogicalKeyEqualFold(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEqualFold(FieldLogicalKey, v))
}

// LogicalKeyContainsFold applies the ContainsFold predicate on the "logical_key" field.
func LogicalKeyContainsFold(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldContainsFold(FieldLogicalKey, v))
}

// RouteFamilyEQ applies the EQ predicate on the "route_family" field.
func RouteFamilyEQ(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldRouteFamily, v))
}

// RouteFamilyNEQ applies the NEQ predicate on the "route_family" field.
func RouteFamilyNEQ(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldRouteFamily, v))
}

// RouteFamilyIn applies the In predicate on the "route_family" field.
func RouteFamilyIn(vs ...string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldRouteFamily, vs...))
}

// RouteFamilyNotIn applies the NotIn predicate on the "route_family" field.
func RouteFamilyNotIn(vs ...string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldRouteFamily, vs...))
}

// RouteFamilyGT applies the GT predicate on the "route_family" field.
func RouteFamilyGT(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldRouteFamily, v))
}

// RouteFamilyGTE applies the GTE predicate on the "route_family" field.
func RouteFamilyGTE(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldRouteFamily, v))
}

// RouteFamilyLT applies the LT predicate on the "route_family" field.
func RouteFamilyLT(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldRouteFamily, v))
}

// RouteFamilyLTE applies the LTE predicate on the "route_family" field.
func RouteFamilyLTE(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldRouteFamily, v))
}

// RouteFamilyContains applies the Contains predicate on the "route_family" field.
func RouteFamilyContains(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldContains(FieldRouteFamily, v))
}

// RouteFamilyHasPrefix applies the HasPrefix predicate on the "route_family" field.
func RouteFamilyHasPrefix(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldHasPrefix(FieldRouteFamily, v))
}

// RouteFamilyHasSuffix applies the HasSuffix predicate on the "route_family" field.
func RouteFamilyHasSuffix(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldHasSuffix(FieldRouteFamily, v))
}

// RouteFamilyEqualFold applies the EqualFold predicate on the "route_family" field.
func RouteFamilyEqualFold(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEqualFold(FieldRouteFamily, v))
}

// RouteFamilyContainsFold applies the ContainsFold predicate on the "route_family" field.
func RouteFamilyContainsFold(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldContainsFold(FieldRouteFamily, v))
}

// ForcedEQ applies the EQ predicate on the "forced" field.
func ForcedEQ(v bool) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldForced, v))
}

// ForcedNEQ applies the NEQ predicate on the "forced" field.
func ForcedNEQ(v bool) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldForced, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotNull(FieldUsageLogID))
}

// CaptureCompletenessEQ applies the EQ predicate on the "capture_completeness" field.
func CaptureCompletenessEQ(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldCaptureCompleteness, v))
}

// CaptureCompletenessNEQ applies the NEQ predicate on the "capture_completeness" field.
func CaptureCompletenessNEQ(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldCaptureCompleteness, v))
}

// CaptureCompletenessIn applies the In predicate on the "capture_completeness" field.
func CaptureCompletenessIn(vs ...string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldCaptureCompleteness, vs...))
}

// CaptureCompletenessNotIn applies the NotIn predicate on the "capture_completeness" field.
func CaptureCompletenessNotIn(vs ...string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldCaptureCompleteness, vs...))
}

// CaptureCompletenessGT applies the GT predicate on the "capture_completeness" field.
func CaptureCompletenessGT(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldCaptureCompleteness, v))
}

// CaptureCompletenessGTE applies the GTE predicate on the "capture_completeness" field.
func CaptureCompletenessGTE(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldCaptureCompleteness, v))
}

// CaptureCompletenessLT applies the LT predicate on the "capture_completeness" field.
func CaptureCompletenessLT(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldCaptureCompleteness, v))
}

// CaptureCompletenessLTE applies the LTE predicate on the "capture_completeness" field.
func CaptureCompletenessLTE(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldCaptureCompleteness, v))
}

// CaptureCompletenessContains applies the Contains predicate on the "capture_completeness" field.
func CaptureCompletenessContains(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldContains(FieldCaptureCompleteness, v))
}

// CaptureCompletenessHasPrefix applies the HasPrefix predicate on the "capture_completeness" field.
func CaptureCompletenessHasPrefix(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldHasPrefix(FieldCaptureCompleteness, v))
}

// CaptureCompletenessHasSuffix applies the HasSuffix predicate on the "capture_completeness" field.
func CaptureCompletenessHasSuffix(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldHasSuffix(FieldCaptureCompleteness, v))
}

// CaptureCompletenessEqualFold applies the EqualFold predicate on the "capture_completeness" field.
func CaptureCompletenessEqualFold(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEqualFold(FieldCaptureCompleteness, v))
}

// CaptureCompletenessContainsFold applies the ContainsFold predicate on the "capture_completeness" field.
func CaptureCompletenessContainsFold(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldContainsFold(FieldCaptureCompleteness, v))
}

// CaptureReasonEQ applies the EQ predicate on the "capture_reason" field.
func CaptureReasonEQ(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldCaptureReason, v))
}

// CaptureReasonNEQ applies the NEQ predicate on the "capture_reason" field.
func CaptureReasonNEQ(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldCaptureReason, v))
}

// CaptureReasonIn applies the In predicate on the "capture_reason" field.
func CaptureReasonIn(vs ...string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldCaptureReason, vs...))
}

// CaptureReasonNotIn applies the NotIn predicate on the "capture_reason" field.
func CaptureReasonNotIn(vs ...string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldCaptureReason, vs...))
}

// CaptureReasonGT applies the GT predicate on the "capture_reason" field.
func CaptureReasonGT(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldCaptureReason, v))
}

// CaptureReasonGTE applies the GTE predicate on the "capture_reason" field.
func CaptureReasonGTE(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldCaptureReason, v))
}

// CaptureReasonLT applies the LT predicate on the "capture_reason" field.
func CaptureReasonLT(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldCaptureReason, v))
}

// CaptureReasonLTE applies the LTE predicate on the "capture_reason" field.
func CaptureReasonLTE(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldCaptureReason, v))
}

// CaptureReasonContains applies the Contains predicate on the "capture_reason" field.
func CaptureReasonContains(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldContains(FieldCaptureReason, v))
}

// CaptureReasonHasPrefix applies the HasPrefix predicate on the "capture_reason" field.
func CaptureReasonHasPrefix(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldHasPrefix(FieldCaptureReason, v))
}

// CaptureReasonHasSuffix applies the HasSuffix predicate on the "capture_reason" field.
func CaptureReasonHasSuffix(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldHasSuffix(FieldCaptureReason, v))
}

// CaptureReasonEqualFold applies the EqualFold predicate on the "capture_reason" field.
func CaptureReasonEqualFold(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEqualFold(FieldCaptureReason, v))
}

// CaptureReasonContainsFold applies the ContainsFold predicate on the "capture_reason" field.
func CaptureReasonContainsFold(v string) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldContainsFold(FieldCaptureReason, v))
}

// SendStartedAtEQ applies the EQ predicate on the "send_started_at" field.
func SendStartedAtEQ(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldSendStartedAt, v))
}

// SendStartedAtNEQ applies the NEQ predicate on the "send_started_at" field.
func SendStartedAtNEQ(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldSendStartedAt, v))
}

// SendStartedAtIn applies the In predicate on the "send_started_at" field.
func SendStartedAtIn(vs ...time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldSendStartedAt, vs...))
}

// SendStartedAtNotIn applies the NotIn predicate on the "send_started_at" field.
func SendStartedAtNotIn(vs ...time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldSendStartedAt, vs...))
}

// SendStartedAtGT applies the GT predicate on the "send_started_at" field.
func SendStartedAtGT(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldSendStartedAt, v))
}

// SendStartedAtGTE applies the GTE predicate on the "send_started_at" field.
func SendStartedAtGTE(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldSendStartedAt, v))
}

// SendStartedAtLT applies the LT predicate on the "send_started_at" field.
func SendStartedAtLT(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldSendStartedAt, v))
}

// SendStartedAtLTE applies the LTE predicate on the "send_started_at" field.
func SendStartedAtLTE(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldSendStartedAt, v))
}

// SendStartedAtIsNil applies the IsNil predicate on the "send_started_at" field.
func SendStartedAtIsNil() predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIsNull(FieldSendStartedAt))
}

// SendStartedAtNotNil applies the NotNil predicate on the "send_started_at" field.
func SendStartedAtNotNil() predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotNull(FieldSendStartedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsageLog applies the HasEdge predicate on the "usage_log" edge.
func HasUsageLog() predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogWith applies the HasEdge predicate on the "usage_log" edge with a given conditions (other predicates).
func HasUsageLogWith(preds ...predicate.UsageLog) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(func(s *sql.Selector) {
		step := newUsageLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestAuditReservation) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestAuditReservation) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestAuditReservation) predicate.RequestAuditReservation {
	return predicate.RequestAuditReservation(sql.NotPredicates(p))
}
