// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/requestaudit"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// RequestAuditCreate is the builder for creating a RequestAudit entity.
type RequestAuditCreate struct {
	config
	mutation *RequestAuditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *RequestAuditCreate) SetUsageLogID(v int64) *RequestAuditCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *RequestAuditCreate) SetHeaders(v map[string]interface{}) *RequestAuditCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetEvents sets the "events" field.
func (_c *RequestAuditCreate) SetEvents(v []map[string]interface{}) *RequestAuditCreate {
	_c.mutation.SetEvents(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *RequestAuditCreate) SetAttempts(v []map[string]interface{}) *RequestAuditCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (_c *RequestAuditCreate) SetCaptureCompleteness(v string) *RequestAuditCreate {
	_c.mutation.SetCaptureCompleteness(v)
	return _c
}

// SetNillableCaptureCompleteness sets the "capture_completeness" field if the given value is not nil.
func (_c *RequestAuditCreate) SetNillableCaptureCompleteness(v *string) *RequestAuditCreate {
	if v != nil {
		_c.SetCaptureCompleteness(*v)
	}
	return _c
}

// SetCaptureReason sets the "capture_reason" field.
func (_c *RequestAuditCreate) SetCaptureReason(v string) *RequestAuditCreate {
	_c.mutation.SetCaptureReason(v)
	return _c
}

// SetNillableCaptureReason sets the "capture_reason" field if the given value is not nil.
func (_c *RequestAuditCreate) SetNillableCaptureReason(v *string) *RequestAuditCreate {
	if v != nil {
		_c.SetCaptureReason(*v)
	}
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *RequestAuditCreate) SetRequestFingerprint(v string) *RequestAuditCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_c *RequestAuditCreate) SetNillableRequestFingerprint(v *string) *RequestAuditCreate {
	if v != nil {
		_c.SetRequestFingerprint(*v)
	}
	return _c
}

// SetFingerprintKeyVersion sets the "fingerprint_key_version" field.
func (_c *RequestAuditCreate) SetFingerprintKeyVersion(v int) *RequestAuditCreate {
	_c.mutation.SetFingerprintKeyVersion(v)
	return _c
}

// SetNillableFingerprintKeyVersion sets the "fingerprint_key_version" field if the given value is not nil.
func (_c *RequestAuditCreate) SetNillableFingerprintKeyVersion(v *int) *RequestAuditCreate {
	if v != nil {
		_c.SetFingerprintKeyVersion(*v)
	}
	return _c
}

// SetFingerprintSalt sets the "fingerprint_salt" field.
func (_c *RequestAuditCreate) SetFingerprintSalt(v []byte) *RequestAuditCreate {
	_c.mutation.SetFingerprintSalt(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RequestAuditCreate) SetMetadata(v map[string]interface{}) *RequestAuditCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestAuditCreate) SetCreatedAt(v time.Time) *RequestAuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestAuditCreate) SetNillableCreatedAt(v *time.Time) *RequestAuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_c *RequestAuditCreate) SetUsageLog(v *UsageLog) *RequestAuditCreate {
	return _c.SetUsageLogID(v.ID)
}

// Mutation returns the RequestAuditMutation object of the builder.
func (_c *RequestAuditCreate) Mutation() *RequestAuditMutation {
	return _c.mutation
}

// Save creates the RequestAudit in the database.
func (_c *RequestAuditCreate) Save(ctx context.Context) (*RequestAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestAuditCreate) SaveX(ctx context.Context) *RequestAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestAuditCreate) defaults() {
	if _, ok := _c.mutation.Headers(); !ok {
		v := requestaudit.DefaultHeaders
		_c.mutation.SetHeaders(v)
	}
	if _, ok := _c.mutation.Events(); !ok {
		v := requestaudit.DefaultEvents
		_c.mutation.SetEvents(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := requestaudit.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.CaptureCompleteness(); !ok {
		v := requestaudit.DefaultCaptureCompleteness
		_c.mutation.SetCaptureCompleteness(v)
	}
	if _, ok := _c.mutation.CaptureReason(); !ok {
		v := requestaudit.DefaultCaptureReason
		_c.mutation.SetCaptureReason(v)
	}
	if _, ok := _c.mutation.FingerprintKeyVersion(); !ok {
		v := requestaudit.DefaultFingerprintKeyVersion
		_c.mutation.SetFingerprintKeyVersion(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := requestaudit.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestaudit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestAuditCreate) check() error {
	if _, ok := _c.mutation.UsageLogID(); !ok {
		return &ValidationError{Name: "usage_log_id", err: errors.New(`ent: missing required field "RequestAudit.usage_log_id"`)}
	}
	if _, ok := _c.mutation.Headers(); !ok {
		return &ValidationError{Name: "headers", err: errors.New(`ent: missing required field "RequestAudit.headers"`)}
	}
	if _, ok := _c.mutation.Events(); !ok {
		return &ValidationError{Name: "events", err: errors.New(`ent: missing required field "RequestAudit.events"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "RequestAudit.attempts"`)}
	}
	if _, ok := _c.mutation.CaptureCompleteness(); !ok {
		return &ValidationError{Name: "capture_completeness", err: errors.New(`ent: missing required field "RequestAudit.capture_completeness"`)}
	}
	if _, ok := _c.mutation.CaptureReason(); !ok {
		return &ValidationError{Name: "capture_reason", err: errors.New(`ent: missing required field "RequestAudit.capture_reason"`)}
	}
	if _, ok := _c.mutation.FingerprintKeyVersion(); !ok {
		return &ValidationError{Name: "fingerprint_key_version", err: errors.New(`ent: missing required field "RequestAudit.fingerprint_key_version"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "RequestAudit.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestAudit.created_at"`)}
	}
	if len(_c.mutation.UsageLogIDs()) == 0 {
		return &ValidationError{Name: "usage_log", err: errors.New(`ent: missing required edge "RequestAudit.usage_log"`)}
	}
	return nil
}

func (_c *RequestAuditCreate) sqlSave(ctx context.Context) (*RequestAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestAuditCreate) createSpec() (*RequestAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestaudit.Table, sqlgraph.NewFieldSpec(requestaudit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(requestaudit.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Events(); ok {
		_spec.SetField(requestaudit.FieldEvents, field.TypeJSON, value)
		_node.Events = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(requestaudit.FieldAttempts, field.TypeJSON, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.CaptureCompleteness(); ok {
		_spec.SetField(requestaudit.FieldCaptureCompleteness, field.TypeString, value)
		_node.CaptureCompleteness = value
	}
	if value, ok := _c.mutation.CaptureReason(); ok {
		_spec.SetField(requestaudit.FieldCaptureReason, field.TypeString, value)
		_node.CaptureReason = value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(requestaudit.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = &value
	}
	if value, ok := _c.mutation.FingerprintKeyVersion(); ok {
		_spec.SetField(requestaudit.FieldFingerprintKeyVersion, field.TypeInt, value)
		_node.FingerprintKeyVersion = value
	}
	if value, ok := _c.mutation.FingerprintSalt(); ok {
		_spec.SetField(requestaudit.FieldFingerprintSalt, field.TypeBytes, value)
		_node.FingerprintSalt = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(requestaudit.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestaudit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestaudit.UsageLogTable,
			Columns: []string{requestaudit.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsageLogID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestAudit.Create().
//		SetUsageLogID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestAuditUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestAuditCreate) OnConflict(opts ...sql.ConflictOption) *RequestAuditUpsertOne {
	_c.conflict = opts
	return &RequestAuditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestAuditCreate) OnConflictColumns(columns ...string) *RequestAuditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestAuditUpsertOne{
		create: _c,
	}
}

type (
	// RequestAuditUpsertOne is the builder for "upsert"-ing
	//  one RequestAudit node.
	RequestAuditUpsertOne struct {
		create *RequestAuditCreate
	}

	// RequestAuditUpsert is the "OnConflict" setter.
	RequestAuditUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsageLogID sets the "usage_log_id" field.
func (u *RequestAuditUpsert) SetUsageLogID(v int64) *RequestAuditUpsert {
	u.Set(requestaudit.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateUsageLogID() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldUsageLogID)
	return u
}

// SetHeaders sets the "headers" field.
func (u *RequestAuditUpsert) SetHeaders(v map[string]interface{}) *RequestAuditUpsert {
	u.Set(requestaudit.FieldHeaders, v)
	return u
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateHeaders() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldHeaders)
	return u
}

// SetEvents sets the "events" field.
func (u *RequestAuditUpsert) SetEvents(v []map[string]interface{}) *RequestAuditUpsert {
	u.Set(requestaudit.FieldEvents, v)
	return u
}

// UpdateEvents sets the "events" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateEvents() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldEvents)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *RequestAuditUpsert) SetAttempts(v []map[string]interface{}) *RequestAuditUpsert {
	u.Set(requestaudit.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateAttempts() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldAttempts)
	return u
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (u *RequestAuditUpsert) SetCaptureCompleteness(v string) *RequestAuditUpsert {
	u.Set(requestaudit.FieldCaptureCompleteness, v)
	return u
}

// UpdateCaptureCompleteness sets the "capture_completeness" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateCaptureCompleteness() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldCaptureCompleteness)
	return u
}

// SetCaptureReason sets the "capture_reason" field.
func (u *RequestAuditUpsert) SetCaptureReason(v string) *RequestAuditUpsert {
	u.Set(requestaudit.FieldCaptureReason, v)
	return u
}

// UpdateCaptureReason sets the "capture_reason" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateCaptureReason() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldCaptureReason)
	return u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *RequestAuditUpsert) SetRequestFingerprint(v string) *RequestAuditUpsert {
	u.Set(requestaudit.FieldRequestFingerprint, v)
	return u
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateRequestFingerprint() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldRequestFingerprint)
	return u
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (u *RequestAuditUpsert) ClearRequestFingerprint() *RequestAuditUpsert {
	u.SetNull(requestaudit.FieldRequestFingerprint)
	return u
}

// SetFingerprintKeyVersion sets the "fingerprint_key_version" field.
func (u *RequestAuditUpsert) SetFingerprintKeyVersion(v int) *RequestAuditUpsert {
	u.Set(requestaudit.FieldFingerprintKeyVersion, v)
	return u
}

// UpdateFingerprintKeyVersion sets the "fingerprint_key_version" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateFingerprintKeyVersion() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldFingerprintKeyVersion)
	return u
}

// AddFingerprintKeyVersion adds v to the "fingerprint_key_version" field.
func (u *RequestAuditUpsert) AddFingerprintKeyVersion(v int) *RequestAuditUpsert {
	u.Add(requestaudit.FieldFingerprintKeyVersion, v)
	return u
}

// SetFingerprintSalt sets the "fingerprint_salt" field.
func (u *RequestAuditUpsert) SetFingerprintSalt(v []byte) *RequestAuditUpsert {
	u.Set(requestaudit.FieldFingerprintSalt, v)
	return u
}

// UpdateFingerprintSalt sets the "fingerprint_salt" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateFingerprintSalt() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldFingerprintSalt)
	return u
}

// ClearFingerprintSalt clears the value of the "fingerprint_salt" field.
func (u *RequestAuditUpsert) ClearFingerprintSalt() *RequestAuditUpsert {
	u.SetNull(requestaudit.FieldFingerprintSalt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *RequestAuditUpsert) SetMetadata(v map[string]interface{}) *RequestAuditUpsert {
	u.Set(requestaudit.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RequestAuditUpsert) UpdateMetadata() *RequestAuditUpsert {
	u.SetExcluded(requestaudit.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestAuditUpsertOne) UpdateNewValues() *RequestAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestaudit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestAudit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestAuditUpsertOne) Ignore() *RequestAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestAuditUpsertOne) DoNothing() *RequestAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestAuditCreate.OnConflict
// documentation for more info.
func (u *RequestAuditUpsertOne) Update(set func(*RequestAuditUpsert)) *RequestAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *RequestAuditUpsertOne) SetUsageLogID(v int64) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateUsageLogID() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetHeaders sets the "headers" field.
func (u *RequestAuditUpsertOne) SetHeaders(v map[string]interface{}) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateHeaders() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateHeaders()
	})
}

// SetEvents sets the "events" field.
func (u *RequestAuditUpsertOne) SetEvents(v []map[string]interface{}) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetEvents(v)
	})
}

// UpdateEvents sets the "events" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateEvents() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateEvents()
	})
}

// SetAttempts sets the "attempts" field.
func (u *RequestAuditUpsertOne) SetAttempts(v []map[string]interface{}) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateAttempts() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateAttempts()
	})
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (u *RequestAuditUpsertOne) SetCaptureCompleteness(v string) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetCaptureCompleteness(v)
	})
}

// UpdateCaptureCompleteness sets the "capture_completeness" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateCaptureCompleteness() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateCaptureCompleteness()
	})
}

// SetCaptureReason sets the "capture_reason" field.
func (u *RequestAuditUpsertOne) SetCaptureReason(v string) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetCaptureReason(v)
	})
}

// UpdateCaptureReason sets the "capture_reason" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateCaptureReason() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateCaptureReason()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *RequestAuditUpsertOne) SetRequestFingerprint(v string) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateRequestFingerprint() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (u *RequestAuditUpsertOne) ClearRequestFingerprint() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.ClearRequestFingerprint()
	})
}

// SetFingerprintKeyVersion sets the "fingerprint_key_version" field.
func (u *RequestAuditUpsertOne) SetFingerprintKeyVersion(v int) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetFingerprintKeyVersion(v)
	})
}

// AddFingerprintKeyVersion adds v to the "fingerprint_key_version" field.
func (u *RequestAuditUpsertOne) AddFingerprintKeyVersion(v int) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.AddFingerprintKeyVersion(v)
	})
}

// UpdateFingerprintKeyVersion sets the "fingerprint_key_version" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateFingerprintKeyVersion() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateFingerprintKeyVersion()
	})
}

// SetFingerprintSalt sets the "fingerprint_salt" field.
func (u *RequestAuditUpsertOne) SetFingerprintSalt(v []byte) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetFingerprintSalt(v)
	})
}

// UpdateFingerprintSalt sets the "fingerprint_salt" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateFingerprintSalt() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateFingerprintSalt()
	})
}

// ClearFingerprintSalt clears the value of the "fingerprint_salt" field.
func (u *RequestAuditUpsertOne) ClearFingerprintSalt() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.ClearFingerprintSalt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RequestAuditUpsertOne) SetMetadata(v map[string]interface{}) *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RequestAuditUpsertOne) UpdateMetadata() *RequestAuditUpsertOne {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *RequestAuditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestAuditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestAuditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestAuditUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestAuditUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestAuditCreateBulk is the builder for creating many RequestAudit entities in bulk.
type RequestAuditCreateBulk struct {
	config
	err      error
	builders []*RequestAuditCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestAudit entities in the database.
func (_c *RequestAuditCreateBulk) Save(ctx context.Context) ([]*RequestAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestAuditCreateBulk) SaveX(ctx context.Context) []*RequestAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestAudit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestAuditUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestAuditCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestAuditUpsertBulk {
	_c.conflict = opts
	return &RequestAuditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestAuditCreateBulk) OnConflictColumns(columns ...string) *RequestAuditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestAuditUpsertBulk{
		create: _c,
	}
}

// RequestAuditUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestAudit nodes.
type RequestAuditUpsertBulk struct {
	create *RequestAuditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestAuditUpsertBulk) UpdateNewValues() *RequestAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestaudit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestAudit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestAuditUpsertBulk) Ignore() *RequestAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestAuditUpsertBulk) DoNothing() *RequestAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestAuditCreateBulk.OnConflict
// documentation for more info.
func (u *RequestAuditUpsertBulk) Update(set func(*RequestAuditUpsert)) *RequestAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *RequestAuditUpsertBulk) SetUsageLogID(v int64) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateUsageLogID() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetHeaders sets the "headers" field.
func (u *RequestAuditUpsertBulk) SetHeaders(v map[string]interface{}) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateHeaders() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateHeaders()
	})
}

// SetEvents sets the "events" field.
func (u *RequestAuditUpsertBulk) SetEvents(v []map[string]interface{}) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetEvents(v)
	})
}

// UpdateEvents sets the "events" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateEvents() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateEvents()
	})
}

// SetAttempts sets the "attempts" field.
func (u *RequestAuditUpsertBulk) SetAttempts(v []map[string]interface{}) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateAttempts() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateAttempts()
	})
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (u *RequestAuditUpsertBulk) SetCaptureCompleteness(v string) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetCaptureCompleteness(v)
	})
}

// UpdateCaptureCompleteness sets the "capture_completeness" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateCaptureCompleteness() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateCaptureCompleteness()
	})
}

// SetCaptureReason sets the "capture_reason" field.
func (u *RequestAuditUpsertBulk) SetCaptureReason(v string) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetCaptureReason(v)
	})
}

// UpdateCaptureReason sets the "capture_reason" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateCaptureReason() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateCaptureReason()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *RequestAuditUpsertBulk) SetRequestFingerprint(v string) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateRequestFingerprint() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (u *RequestAuditUpsertBulk) ClearRequestFingerprint() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.ClearRequestFingerprint()
	})
}

// SetFingerprintKeyVersion sets the "fingerprint_key_version" field.
func (u *RequestAuditUpsertBulk) SetFingerprintKeyVersion(v int) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetFingerprintKeyVersion(v)
	})
}

// AddFingerprintKeyVersion adds v to the "fingerprint_key_version" field.
func (u *RequestAuditUpsertBulk) AddFingerprintKeyVersion(v int) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.AddFingerprintKeyVersion(v)
	})
}

// UpdateFingerprintKeyVersion sets the "fingerprint_key_version" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateFingerprintKeyVersion() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateFingerprintKeyVersion()
	})
}

// SetFingerprintSalt sets the "fingerprint_salt" field.
func (u *RequestAuditUpsertBulk) SetFingerprintSalt(v []byte) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetFingerprintSalt(v)
	})
}

// UpdateFingerprintSalt sets the "fingerprint_salt" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateFingerprintSalt() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateFingerprintSalt()
	})
}

// ClearFingerprintSalt clears the value of the "fingerprint_salt" field.
func (u *RequestAuditUpsertBulk) ClearFingerprintSalt() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.ClearFingerprintSalt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RequestAuditUpsertBulk) SetMetadata(v map[string]interface{}) *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RequestAuditUpsertBulk) UpdateMetadata() *RequestAuditUpsertBulk {
	return u.Update(func(s *RequestAuditUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *RequestAuditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestAuditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestAuditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestAuditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
