// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/requestauditreservation"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// RequestAuditReservationCreate is the builder for creating a RequestAuditReservation entity.
type RequestAuditReservationCreate struct {
	config
	mutation *RequestAuditReservationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLogicalKey sets the "logical_key" field.
func (_c *RequestAuditReservationCreate) SetLogicalKey(v string) *RequestAuditReservationCreate {
	_c.mutation.SetLogicalKey(v)
	return _c
}

// SetRouteFamily sets the "route_family" field.
func (_c *RequestAuditReservationCreate) SetRouteFamily(v string) *RequestAuditReservationCreate {
	_c.mutation.SetRouteFamily(v)
	return _c
}

// SetForced sets the "forced" field.
func (_c *RequestAuditReservationCreate) SetForced(v bool) *RequestAuditReservationCreate {
	_c.mutation.SetForced(v)
	return _c
}

// SetNillableForced sets the "forced" field if the given value is not nil.
func (_c *RequestAuditReservationCreate) SetNillableForced(v *bool) *RequestAuditReservationCreate {
	if v != nil {
		_c.SetForced(*v)
	}
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *RequestAuditReservationCreate) SetHeaders(v map[string]interface{}) *RequestAuditReservationCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *RequestAuditReservationCreate) SetAttempts(v []map[string]interface{}) *RequestAuditReservationCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *RequestAuditReservationCreate) SetUsageLogID(v int64) *RequestAuditReservationCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *RequestAuditReservationCreate) SetNillableUsageLogID(v *int64) *RequestAuditReservationCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (_c *RequestAuditReservationCreate) SetCaptureCompleteness(v string) *RequestAuditReservationCreate {
	_c.mutation.SetCaptureCompleteness(v)
	return _c
}

// SetNillableCaptureCompleteness sets the "capture_completeness" field if the given value is not nil.
func (_c *RequestAuditReservationCreate) SetNillableCaptureCompleteness(v *string) *RequestAuditReservationCreate {
	if v != nil {
		_c.SetCaptureCompleteness(*v)
	}
	return _c
}

// SetCaptureReason sets the "capture_reason" field.
func (_c *RequestAuditReservationCreate) SetCaptureReason(v string) *RequestAuditReservationCreate {
	_c.mutation.SetCaptureReason(v)
	return _c
}

// SetNillableCaptureReason sets the "capture_reason" field if the given value is not nil.
func (_c *RequestAuditReservationCreate) SetNillableCaptureReason(v *string) *RequestAuditReservationCreate {
	if v != nil {
		_c.SetCaptureReason(*v)
	}
	return _c
}

// SetSendStartedAt sets the "send_started_at" field.
func (_c *RequestAuditReservationCreate) SetSendStartedAt(v time.Time) *RequestAuditReservationCreate {
	_c.mutation.SetSendStartedAt(v)
	return _c
}

// SetNillableSendStartedAt sets the "send_started_at" field if the given value is not nil.
func (_c *RequestAuditReservationCreate) SetNillableSendStartedAt(v *time.Time) *RequestAuditReservationCreate {
	if v != nil {
		_c.SetSendStartedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *RequestAuditReservationCreate) SetExpiresAt(v time.Time) *RequestAuditReservationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestAuditReservationCreate) SetCreatedAt(v time.Time) *RequestAuditReservationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestAuditReservationCreate) SetNillableCreatedAt(v *time.Time) *RequestAuditReservationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RequestAuditReservationCreate) SetUpdatedAt(v time.Time) *RequestAuditReservationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RequestAuditReservationCreate) SetNillableUpdatedAt(v *time.Time) *RequestAuditReservationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_c *RequestAuditReservationCreate) SetUsageLog(v *UsageLog) *RequestAuditReservationCreate {
	return _c.SetUsageLogID(v.ID)
}

// Mutation returns the RequestAuditReservationMutation object of the builder.
func (_c *RequestAuditReservationCreate) Mutation() *RequestAuditReservationMutation {
	return _c.mutation
}

// Save creates the RequestAuditReservation in the database.
func (_c *RequestAuditReservationCreate) Save(ctx context.Context) (*RequestAuditReservation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestAuditReservationCreate) SaveX(ctx context.Context) *RequestAuditReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestAuditReservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestAuditReservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestAuditReservationCreate) defaults() {
	if _, ok := _c.mutation.Forced(); !ok {
		v := requestauditreservation.DefaultForced
		_c.mutation.SetForced(v)
	}
	if _, ok := _c.mutation.Headers(); !ok {
		v := requestauditreservation.DefaultHeaders
		_c.mutation.SetHeaders(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := requestauditreservation.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.CaptureCompleteness(); !ok {
		v := requestauditreservation.DefaultCaptureCompleteness
		_c.mutation.SetCaptureCompleteness(v)
	}
	if _, ok := _c.mutation.CaptureReason(); !ok {
		v := requestauditreservation.DefaultCaptureReason
		_c.mutation.SetCaptureReason(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestauditreservation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := requestauditreservation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestAuditReservationCreate) check() error {
	if _, ok := _c.mutation.LogicalKey(); !ok {
		return &ValidationError{Name: "logical_key", err: errors.New(`ent: missing required field "RequestAuditReservation.logical_key"`)}
	}
	if v, ok := _c.mutation.LogicalKey(); ok {
		if err := requestauditreservation.LogicalKeyValidator(v); err != nil {
			return &ValidationError{Name: "logical_key", err: fmt.Errorf(`ent: validator failed for field "RequestAuditReservation.logical_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RouteFamily(); !ok {
		return &ValidationError{Name: "route_family", err: errors.New(`ent: missing required field "RequestAuditReservation.route_family"`)}
	}
	if v, ok := _c.mutation.RouteFamily(); ok {
		if err := requestauditreservation.RouteFamilyValidator(v); err != nil {
			return &ValidationError{Name: "route_family", err: fmt.Errorf(`ent: validator failed for field "RequestAuditReservation.route_family": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Forced(); !ok {
		return &ValidationError{Name: "forced", err: errors.New(`ent: missing required field "RequestAuditReservation.forced"`)}
	}
	if _, ok := _c.mutation.Headers(); !ok {
		return &ValidationError{Name: "headers", err: errors.New(`ent: missing required field "RequestAuditReservation.headers"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "RequestAuditReservation.attempts"`)}
	}
	if _, ok := _c.mutation.CaptureCompleteness(); !ok {
		return &ValidationError{Name: "capture_completeness", err: errors.New(`ent: missing required field "RequestAuditReservation.capture_completeness"`)}
	}
	if _, ok := _c.mutation.CaptureReason(); !ok {
		return &ValidationError{Name: "capture_reason", err: errors.New(`ent: missing required field "RequestAuditReservation.capture_reason"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "RequestAuditReservation.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestAuditReservation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RequestAuditReservation.updated_at"`)}
	}
	return nil
}

func (_c *RequestAuditReservationCreate) sqlSave(ctx context.Context) (*RequestAuditReservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestAuditReservationCreate) createSpec() (*RequestAuditReservation, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestAuditReservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestauditreservation.Table, sqlgraph.NewFieldSpec(requestauditreservation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.LogicalKey(); ok {
		_spec.SetField(requestauditreservation.FieldLogicalKey, field.TypeString, value)
		_node.LogicalKey = value
	}
	if value, ok := _c.mutation.RouteFamily(); ok {
		_spec.SetField(requestauditreservation.FieldRouteFamily, field.TypeString, value)
		_node.RouteFamily = value
	}
	if value, ok := _c.mutation.Forced(); ok {
		_spec.SetField(requestauditreservation.FieldForced, field.TypeBool, value)
		_node.Forced = value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(requestauditreservation.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(requestauditreservation.FieldAttempts, field.TypeJSON, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.CaptureCompleteness(); ok {
		_spec.SetField(requestauditreservation.FieldCaptureCompleteness, field.TypeString, value)
		_node.CaptureCompleteness = value
	}
	if value, ok := _c.mutation.CaptureReason(); ok {
		_spec.SetField(requestauditreservation.FieldCaptureReason, field.TypeString, value)
		_node.CaptureReason = value
	}
	if value, ok := _c.mutation.SendStartedAt(); ok {
		_spec.SetField(requestauditreservation.FieldSendStartedAt, field.TypeTime, value)
		_node.SendStartedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(requestauditreservation.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestauditreservation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(requestauditreservation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestauditreservation.UsageLogTable,
			Columns: []string{requestauditreservation.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsageLogID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestAuditReservation.Create().
//		SetLogicalKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestAuditReservationUpsert) {
//			SetLogicalKey(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestAuditReservationCreate) OnConflict(opts ...sql.ConflictOption) *RequestAuditReservationUpsertOne {
	_c.conflict = opts
	return &RequestAuditReservationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestAuditReservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestAuditReservationCreate) OnConflictColumns(columns ...string) *RequestAuditReservationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestAuditReservationUpsertOne{
		create: _c,
	}
}

type (
	// RequestAuditReservationUpsertOne is the builder for "upsert"-ing
	//  one RequestAuditReservation node.
	RequestAuditReservationUpsertOne struct {
		create *RequestAuditReservationCreate
	}

	// RequestAuditReservationUpsert is the "OnConflict" setter.
	RequestAuditReservationUpsert struct {
		*sql.UpdateSet
	}
)

// SetLogicalKey sets the "logical_key" field.
func (u *RequestAuditReservationUpsert) SetLogicalKey(v string) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldLogicalKey, v)
	return u
}

// UpdateLogicalKey sets the "logical_key" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateLogicalKey() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldLogicalKey)
	return u
}

// SetRouteFamily sets the "route_family" field.
func (u *RequestAuditReservationUpsert) SetRouteFamily(v string) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldRouteFamily, v)
	return u
}

// UpdateRouteFamily sets the "route_family" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateRouteFamily() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldRouteFamily)
	return u
}

// SetForced sets the "forced" field.
func (u *RequestAuditReservationUpsert) SetForced(v bool) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldForced, v)
	return u
}

// UpdateForced sets the "forced" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateForced() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldForced)
	return u
}

// SetHeaders sets the "headers" field.
func (u *RequestAuditReservationUpsert) SetHeaders(v map[string]interface{}) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldHeaders, v)
	return u
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateHeaders() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldHeaders)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *RequestAuditReservationUpsert) SetAttempts(v []map[string]interface{}) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateAttempts() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldAttempts)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *RequestAuditReservationUpsert) SetUsageLogID(v int64) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateUsageLogID() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldUsageLogID)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *RequestAuditReservationUpsert) ClearUsageLogID() *RequestAuditReservationUpsert {
	u.SetNull(requestauditreservation.FieldUsageLogID)
	return u
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (u *RequestAuditReservationUpsert) SetCaptureCompleteness(v string) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldCaptureCompleteness, v)
	return u
}

// UpdateCaptureCompleteness sets the "capture_completeness" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateCaptureCompleteness() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldCaptureCompleteness)
	return u
}

// SetCaptureReason sets the "capture_reason" field.
func (u *RequestAuditReservationUpsert) SetCaptureReason(v string) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldCaptureReason, v)
	return u
}

// UpdateCaptureReason sets the "capture_reason" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateCaptureReason() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldCaptureReason)
	return u
}

// SetSendStartedAt sets the "send_started_at" field.
func (u *RequestAuditReservationUpsert) SetSendStartedAt(v time.Time) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldSendStartedAt, v)
	return u
}

// UpdateSendStartedAt sets the "send_started_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateSendStartedAt() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldSendStartedAt)
	return u
}

// ClearSendStartedAt clears the value of the "send_started_at" field.
func (u *RequestAuditReservationUpsert) ClearSendStartedAt() *RequestAuditReservationUpsert {
	u.SetNull(requestauditreservation.FieldSendStartedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *RequestAuditReservationUpsert) SetExpiresAt(v time.Time) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateExpiresAt() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldExpiresAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestAuditReservationUpsert) SetUpdatedAt(v time.Time) *RequestAuditReservationUpsert {
	u.Set(requestauditreservation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsert) UpdateUpdatedAt() *RequestAuditReservationUpsert {
	u.SetExcluded(requestauditreservation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestAuditReservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestAuditReservationUpsertOne) UpdateNewValues() *RequestAuditReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestauditreservation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestAuditReservation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestAuditReservationUpsertOne) Ignore() *RequestAuditReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestAuditReservationUpsertOne) DoNothing() *RequestAuditReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestAuditReservationCreate.OnConflict
// documentation for more info.
func (u *RequestAuditReservationUpsertOne) Update(set func(*RequestAuditReservationUpsert)) *RequestAuditReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestAuditReservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetLogicalKey sets the "logical_key" field.
func (u *RequestAuditReservationUpsertOne) SetLogicalKey(v string) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetLogicalKey(v)
	})
}

// UpdateLogicalKey sets the "logical_key" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateLogicalKey() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateLogicalKey()
	})
}

// SetRouteFamily sets the "route_family" field.
func (u *RequestAuditReservationUpsertOne) SetRouteFamily(v string) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetRouteFamily(v)
	})
}

// UpdateRouteFamily sets the "route_family" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateRouteFamily() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateRouteFamily()
	})
}

// SetForced sets the "forced" field.
func (u *RequestAuditReservationUpsertOne) SetForced(v bool) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetForced(v)
	})
}

// UpdateForced sets the "forced" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateForced() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateForced()
	})
}

// SetHeaders sets the "headers" field.
func (u *RequestAuditReservationUpsertOne) SetHeaders(v map[string]interface{}) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateHeaders() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateHeaders()
	})
}

// SetAttempts sets the "attempts" field.
func (u *RequestAuditReservationUpsertOne) SetAttempts(v []map[string]interface{}) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateAttempts() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateAttempts()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *RequestAuditReservationUpsertOne) SetUsageLogID(v int64) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateUsageLogID() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *RequestAuditReservationUpsertOne) ClearUsageLogID() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.ClearUsageLogID()
	})
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (u *RequestAuditReservationUpsertOne) SetCaptureCompleteness(v string) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetCaptureCompleteness(v)
	})
}

// UpdateCaptureCompleteness sets the "capture_completeness" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateCaptureCompleteness() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateCaptureCompleteness()
	})
}

// SetCaptureReason sets the "capture_reason" field.
func (u *RequestAuditReservationUpsertOne) SetCaptureReason(v string) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetCaptureReason(v)
	})
}

// UpdateCaptureReason sets the "capture_reason" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateCaptureReason() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateCaptureReason()
	})
}

// SetSendStartedAt sets the "send_started_at" field.
func (u *RequestAuditReservationUpsertOne) SetSendStartedAt(v time.Time) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetSendStartedAt(v)
	})
}

// UpdateSendStartedAt sets the "send_started_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateSendStartedAt() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateSendStartedAt()
	})
}

// ClearSendStartedAt clears the value of the "send_started_at" field.
func (u *RequestAuditReservationUpsertOne) ClearSendStartedAt() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.ClearSendStartedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RequestAuditReservationUpsertOne) SetExpiresAt(v time.Time) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateExpiresAt() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestAuditReservationUpsertOne) SetUpdatedAt(v time.Time) *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertOne) UpdateUpdatedAt() *RequestAuditReservationUpsertOne {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RequestAuditReservationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestAuditReservationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestAuditReservationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestAuditReservationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestAuditReservationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestAuditReservationCreateBulk is the builder for creating many RequestAuditReservation entities in bulk.
type RequestAuditReservationCreateBulk struct {
	config
	err      error
	builders []*RequestAuditReservationCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestAuditReservation entities in the database.
func (_c *RequestAuditReservationCreateBulk) Save(ctx context.Context) ([]*RequestAuditReservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestAuditReservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestAuditReservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestAuditReservationCreateBulk) SaveX(ctx context.Context) []*RequestAuditReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestAuditReservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestAuditReservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestAuditReservation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestAuditReservationUpsert) {
//			SetLogicalKey(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestAuditReservationCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestAuditReservationUpsertBulk {
	_c.conflict = opts
	return &RequestAuditReservationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestAuditReservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestAuditReservationCreateBulk) OnConflictColumns(columns ...string) *RequestAuditReservationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestAuditReservationUpsertBulk{
		create: _c,
	}
}

// RequestAuditReservationUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestAuditReservation nodes.
type RequestAuditReservationUpsertBulk struct {
	create *RequestAuditReservationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestAuditReservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestAuditReservationUpsertBulk) UpdateNewValues() *RequestAuditReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestauditreservation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestAuditReservation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestAuditReservationUpsertBulk) Ignore() *RequestAuditReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestAuditReservationUpsertBulk) DoNothing() *RequestAuditReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestAuditReservationCreateBulk.OnConflict
// documentation for more info.
func (u *RequestAuditReservationUpsertBulk) Update(set func(*RequestAuditReservationUpsert)) *RequestAuditReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestAuditReservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetLogicalKey sets the "logical_key" field.
func (u *RequestAuditReservationUpsertBulk) SetLogicalKey(v string) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetLogicalKey(v)
	})
}

// UpdateLogicalKey sets the "logical_key" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateLogicalKey() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateLogicalKey()
	})
}

// SetRouteFamily sets the "route_family" field.
func (u *RequestAuditReservationUpsertBulk) SetRouteFamily(v string) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetRouteFamily(v)
	})
}

// UpdateRouteFamily sets the "route_family" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateRouteFamily() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateRouteFamily()
	})
}

// SetForced sets the "forced" field.
func (u *RequestAuditReservationUpsertBulk) SetForced(v bool) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetForced(v)
	})
}

// UpdateForced sets the "forced" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateForced() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateForced()
	})
}

// SetHeaders sets the "headers" field.
func (u *RequestAuditReservationUpsertBulk) SetHeaders(v map[string]interface{}) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateHeaders() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateHeaders()
	})
}

// SetAttempts sets the "attempts" field.
func (u *RequestAuditReservationUpsertBulk) SetAttempts(v []map[string]interface{}) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateAttempts() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateAttempts()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *RequestAuditReservationUpsertBulk) SetUsageLogID(v int64) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateUsageLogID() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *RequestAuditReservationUpsertBulk) ClearUsageLogID() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.ClearUsageLogID()
	})
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (u *RequestAuditReservationUpsertBulk) SetCaptureCompleteness(v string) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetCaptureCompleteness(v)
	})
}

// UpdateCaptureCompleteness sets the "capture_completeness" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateCaptureCompleteness() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateCaptureCompleteness()
	})
}

// SetCaptureReason sets the "capture_reason" field.
func (u *RequestAuditReservationUpsertBulk) SetCaptureReason(v string) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetCaptureReason(v)
	})
}

// UpdateCaptureReason sets the "capture_reason" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateCaptureReason() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateCaptureReason()
	})
}

// SetSendStartedAt sets the "send_started_at" field.
func (u *RequestAuditReservationUpsertBulk) SetSendStartedAt(v time.Time) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetSendStartedAt(v)
	})
}

// UpdateSendStartedAt sets the "send_started_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateSendStartedAt() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateSendStartedAt()
	})
}

// ClearSendStartedAt clears the value of the "send_started_at" field.
func (u *RequestAuditReservationUpsertBulk) ClearSendStartedAt() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.ClearSendStartedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RequestAuditReservationUpsertBulk) SetExpiresAt(v time.Time) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateExpiresAt() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestAuditReservationUpsertBulk) SetUpdatedAt(v time.Time) *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestAuditReservationUpsertBulk) UpdateUpdatedAt() *RequestAuditReservationUpsertBulk {
	return u.Update(func(s *RequestAuditReservationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RequestAuditReservationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestAuditReservationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestAuditReservationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestAuditReservationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
