// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestaudit"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// RequestAuditUpdate is the builder for updating RequestAudit entities.
type RequestAuditUpdate struct {
	config
	hooks    []Hook
	mutation *RequestAuditMutation
}

// Where appends a list predicates to the RequestAuditUpdate builder.
func (_u *RequestAuditUpdate) Where(ps ...predicate.RequestAudit) *RequestAuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *RequestAuditUpdate) SetUsageLogID(v int64) *RequestAuditUpdate {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *RequestAuditUpdate) SetNillableUsageLogID(v *int64) *RequestAuditUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *RequestAuditUpdate) SetHeaders(v map[string]interface{}) *RequestAuditUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetEvents sets the "events" field.
func (_u *RequestAuditUpdate) SetEvents(v []map[string]interface{}) *RequestAuditUpdate {
	_u.mutation.SetEvents(v)
	return _u
}

// AppendEvents appends value to the "events" field.
func (_u *RequestAuditUpdate) AppendEvents(v []map[string]interface{}) *RequestAuditUpdate {
	_u.mutation.AppendEvents(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *RequestAuditUpdate) SetAttempts(v []map[string]interface{}) *RequestAuditUpdate {
	_u.mutation.SetAttempts(v)
	return _u
}

// AppendAttempts appends value to the "attempts" field.
func (_u *RequestAuditUpdate) AppendAttempts(v []map[string]interface{}) *RequestAuditUpdate {
	_u.mutation.AppendAttempts(v)
	return _u
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (_u *RequestAuditUpdate) SetCaptureCompleteness(v string) *RequestAuditUpdate {
	_u.mutation.SetCaptureCompleteness(v)
	return _u
}

// SetNillableCaptureCompleteness sets the "capture_completeness" field if the given value is not nil.
func (_u *RequestAuditUpdate) SetNillableCaptureCompleteness(v *string) *RequestAuditUpdate {
	if v != nil {
		_u.SetCaptureCompleteness(*v)
	}
	return _u
}

// SetCaptureReason sets the "capture_reason" field.
func (_u *RequestAuditUpdate) SetCaptureReason(v string) *RequestAuditUpdate {
	_u.mutation.SetCaptureReason(v)
	return _u
}

// SetNillableCaptureReason sets the "capture_reason" field if the given value is not nil.
func (_u *RequestAuditUpdate) SetNillableCaptureReason(v *string) *RequestAuditUpdate {
	if v != nil {
		_u.SetCaptureReason(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *RequestAuditUpdate) SetRequestFingerprint(v string) *RequestAuditUpdate {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *RequestAuditUpdate) SetNillableRequestFingerprint(v *string) *RequestAuditUpdate {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (_u *RequestAuditUpdate) ClearRequestFingerprint() *RequestAuditUpdate {
	_u.mutation.ClearRequestFingerprint()
	return _u
}

// SetFingerprintKeyVersion sets the "fingerprint_key_version" field.
func (_u *RequestAuditUpdate) SetFingerprintKeyVersion(v int) *RequestAuditUpdate {
	_u.mutation.ResetFingerprintKeyVersion()
	_u.mutation.SetFingerprintKeyVersion(v)
	return _u
}

// SetNillableFingerprintKeyVersion sets the "fingerprint_key_version" field if the given value is not nil.
func (_u *RequestAuditUpdate) SetNillableFingerprintKeyVersion(v *int) *RequestAuditUpdate {
	if v != nil {
		_u.SetFingerprintKeyVersion(*v)
	}
	return _u
}

// AddFingerprintKeyVersion adds value to the "fingerprint_key_version" field.
func (_u *RequestAuditUpdate) AddFingerprintKeyVersion(v int) *RequestAuditUpdate {
	_u.mutation.AddFingerprintKeyVersion(v)
	return _u
}

// SetFingerprintSalt sets the "fingerprint_salt" field.
func (_u *RequestAuditUpdate) SetFingerprintSalt(v []byte) *RequestAuditUpdate {
	_u.mutation.SetFingerprintSalt(v)
	return _u
}

// ClearFingerprintSalt clears the value of the "fingerprint_salt" field.
func (_u *RequestAuditUpdate) ClearFingerprintSalt() *RequestAuditUpdate {
	_u.mutation.ClearFingerprintSalt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RequestAuditUpdate) SetMetadata(v map[string]interface{}) *RequestAuditUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *RequestAuditUpdate) SetUsageLog(v *UsageLog) *RequestAuditUpdate {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the RequestAuditMutation object of the builder.
func (_u *RequestAuditUpdate) Mutation() *RequestAuditMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *RequestAuditUpdate) ClearUsageLog() *RequestAuditUpdate {
	_u.mutation.ClearUsageLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestAuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestAuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestAuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestAuditUpdate) check() error {
	if _u.mutation.UsageLogCleared() && len(_u.mutation.UsageLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestAudit.usage_log"`)
	}
	return nil
}

func (_u *RequestAuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestaudit.Table, requestaudit.Columns, sqlgraph.NewFieldSpec(requestaudit.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(requestaudit.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Events(); ok {
		_spec.SetField(requestaudit.FieldEvents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEvents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestaudit.FieldEvents, value)
		})
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(requestaudit.FieldAttempts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttempts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestaudit.FieldAttempts, value)
		})
	}
	if value, ok := _u.mutation.CaptureCompleteness(); ok {
		_spec.SetField(requestaudit.FieldCaptureCompleteness, field.TypeString, value)
	}
	if value, ok := _u.mutation.CaptureReason(); ok {
		_spec.SetField(requestaudit.FieldCaptureReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(requestaudit.FieldRequestFingerprint, field.TypeString, value)
	}
	if _u.mutation.RequestFingerprintCleared() {
		_spec.ClearField(requestaudit.FieldRequestFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.FingerprintKeyVersion(); ok {
		_spec.SetField(requestaudit.FieldFingerprintKeyVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFingerprintKeyVersion(); ok {
		_spec.AddField(requestaudit.FieldFingerprintKeyVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FingerprintSalt(); ok {
		_spec.SetField(requestaudit.FieldFingerprintSalt, field.TypeBytes, value)
	}
	if _u.mutation.FingerprintSaltCleared() {
		_spec.ClearField(requestaudit.FieldFingerprintSalt, field.TypeBytes)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(requestaudit.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestaudit.UsageLogTable,
			Columns: []string{requestaudit.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestaudit.UsageLogTable,
			Columns: []string{requestaudit.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestAuditUpdateOne is the builder for updating a single RequestAudit entity.
type RequestAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestAuditMutation
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *RequestAuditUpdateOne) SetUsageLogID(v int64) *RequestAuditUpdateOne {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *RequestAuditUpdateOne) SetNillableUsageLogID(v *int64) *RequestAuditUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *RequestAuditUpdateOne) SetHeaders(v map[string]interface{}) *RequestAuditUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetEvents sets the "events" field.
func (_u *RequestAuditUpdateOne) SetEvents(v []map[string]interface{}) *RequestAuditUpdateOne {
	_u.mutation.SetEvents(v)
	return _u
}

// AppendEvents appends value to the "events" field.
func (_u *RequestAuditUpdateOne) AppendEvents(v []map[string]interface{}) *RequestAuditUpdateOne {
	_u.mutation.AppendEvents(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *RequestAuditUpdateOne) SetAttempts(v []map[string]interface{}) *RequestAuditUpdateOne {
	_u.mutation.SetAttempts(v)
	return _u
}

// AppendAttempts appends value to the "attempts" field.
func (_u *RequestAuditUpdateOne) AppendAttempts(v []map[string]interface{}) *RequestAuditUpdateOne {
	_u.mutation.AppendAttempts(v)
	return _u
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (_u *RequestAuditUpdateOne) SetCaptureCompleteness(v string) *RequestAuditUpdateOne {
	_u.mutation.SetCaptureCompleteness(v)
	return _u
}

// SetNillableCaptureCompleteness sets the "capture_completeness" field if the given value is not nil.
func (_u *RequestAuditUpdateOne) SetNillableCaptureCompleteness(v *string) *RequestAuditUpdateOne {
	if v != nil {
		_u.SetCaptureCompleteness(*v)
	}
	return _u
}

// SetCaptureReason sets the "capture_reason" field.
func (_u *RequestAuditUpdateOne) SetCaptureReason(v string) *RequestAuditUpdateOne {
	_u.mutation.SetCaptureReason(v)
	return _u
}

// SetNillableCaptureReason sets the "capture_reason" field if the given value is not nil.
func (_u *RequestAuditUpdateOne) SetNillableCaptureReason(v *string) *RequestAuditUpdateOne {
	if v != nil {
		_u.SetCaptureReason(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *RequestAuditUpdateOne) SetRequestFingerprint(v string) *RequestAuditUpdateOne {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *RequestAuditUpdateOne) SetNillableRequestFingerprint(v *string) *RequestAuditUpdateOne {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// ClearRequestFingerprint clears the value of the "request_fingerprint" field.
func (_u *RequestAuditUpdateOne) ClearRequestFingerprint() *RequestAuditUpdateOne {
	_u.mutation.ClearRequestFingerprint()
	return _u
}

// SetFingerprintKeyVersion sets the "fingerprint_key_version" field.
func (_u *RequestAuditUpdateOne) SetFingerprintKeyVersion(v int) *RequestAuditUpdateOne {
	_u.mutation.ResetFingerprintKeyVersion()
	_u.mutation.SetFingerprintKeyVersion(v)
	return _u
}

// SetNillableFingerprintKeyVersion sets the "fingerprint_key_version" field if the given value is not nil.
func (_u *RequestAuditUpdateOne) SetNillableFingerprintKeyVersion(v *int) *RequestAuditUpdateOne {
	if v != nil {
		_u.SetFingerprintKeyVersion(*v)
	}
	return _u
}

// AddFingerprintKeyVersion adds value to the "fingerprint_key_version" field.
func (_u *RequestAuditUpdateOne) AddFingerprintKeyVersion(v int) *RequestAuditUpdateOne {
	_u.mutation.AddFingerprintKeyVersion(v)
	return _u
}

// SetFingerprintSalt sets the "fingerprint_salt" field.
func (_u *RequestAuditUpdateOne) SetFingerprintSalt(v []byte) *RequestAuditUpdateOne {
	_u.mutation.SetFingerprintSalt(v)
	return _u
}

// ClearFingerprintSalt clears the value of the "fingerprint_salt" field.
func (_u *RequestAuditUpdateOne) ClearFingerprintSalt() *RequestAuditUpdateOne {
	_u.mutation.ClearFingerprintSalt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RequestAuditUpdateOne) SetMetadata(v map[string]interface{}) *RequestAuditUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *RequestAuditUpdateOne) SetUsageLog(v *UsageLog) *RequestAuditUpdateOne {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the RequestAuditMutation object of the builder.
func (_u *RequestAuditUpdateOne) Mutation() *RequestAuditMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *RequestAuditUpdateOne) ClearUsageLog() *RequestAuditUpdateOne {
	_u.mutation.ClearUsageLog()
	return _u
}

// Where appends a list predicates to the RequestAuditUpdate builder.
func (_u *RequestAuditUpdateOne) Where(ps ...predicate.RequestAudit) *RequestAuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestAuditUpdateOne) Select(field string, fields ...string) *RequestAuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestAudit entity.
func (_u *RequestAuditUpdateOne) Save(ctx context.Context) (*RequestAudit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestAuditUpdateOne) SaveX(ctx context.Context) *RequestAudit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestAuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestAuditUpdateOne) check() error {
	if _u.mutation.UsageLogCleared() && len(_u.mutation.UsageLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestAudit.usage_log"`)
	}
	return nil
}

func (_u *RequestAuditUpdateOne) sqlSave(ctx context.Context) (_node *RequestAudit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestaudit.Table, requestaudit.Columns, sqlgraph.NewFieldSpec(requestaudit.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestaudit.FieldID)
		for _, f := range fields {
			if !requestaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(requestaudit.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Events(); ok {
		_spec.SetField(requestaudit.FieldEvents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEvents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestaudit.FieldEvents, value)
		})
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(requestaudit.FieldAttempts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttempts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestaudit.FieldAttempts, value)
		})
	}
	if value, ok := _u.mutation.CaptureCompleteness(); ok {
		_spec.SetField(requestaudit.FieldCaptureCompleteness, field.TypeString, value)
	}
	if value, ok := _u.mutation.CaptureReason(); ok {
		_spec.SetField(requestaudit.FieldCaptureReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(requestaudit.FieldRequestFingerprint, field.TypeString, value)
	}
	if _u.mutation.RequestFingerprintCleared() {
		_spec.ClearField(requestaudit.FieldRequestFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.FingerprintKeyVersion(); ok {
		_spec.SetField(requestaudit.FieldFingerprintKeyVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFingerprintKeyVersion(); ok {
		_spec.AddField(requestaudit.FieldFingerprintKeyVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FingerprintSalt(); ok {
		_spec.SetField(requestaudit.FieldFingerprintSalt, field.TypeBytes, value)
	}
	if _u.mutation.FingerprintSaltCleared() {
		_spec.ClearField(requestaudit.FieldFingerprintSalt, field.TypeBytes)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(requestaudit.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestaudit.UsageLogTable,
			Columns: []string{requestaudit.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestaudit.UsageLogTable,
			Columns: []string{requestaudit.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RequestAudit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
