// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestauditreservation"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// RequestAuditReservationQuery is the builder for querying RequestAuditReservation entities.
type RequestAuditReservationQuery struct {
	config
	ctx          *QueryContext
	order        []requestauditreservation.OrderOption
	inters       []Interceptor
	predicates   []predicate.RequestAuditReservation
	withUsageLog *UsageLogQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RequestAuditReservationQuery builder.
func (_q *RequestAuditReservationQuery) Where(ps ...predicate.RequestAuditReservation) *RequestAuditReservationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RequestAuditReservationQuery) Limit(limit int) *RequestAuditReservationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RequestAuditReservationQuery) Offset(offset int) *RequestAuditReservationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RequestAuditReservationQuery) Unique(unique bool) *RequestAuditReservationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RequestAuditReservationQuery) Order(o ...requestauditreservation.OrderOption) *RequestAuditReservationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUsageLog chains the current query on the "usage_log" edge.
func (_q *RequestAuditReservationQuery) QueryUsageLog() *UsageLogQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(requestauditreservation.Table, requestauditreservation.FieldID, selector),
			sqlgraph.To(usagelog.Table, usagelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, requestauditreservation.UsageLogTable, requestauditreservation.UsageLogColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RequestAuditReservation entity from the query.
// Returns a *NotFoundError when no RequestAuditReservation was found.
func (_q *RequestAuditReservationQuery) First(ctx context.Context) (*RequestAuditReservation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{requestauditreservation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RequestAuditReservationQuery) FirstX(ctx context.Context) *RequestAuditReservation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RequestAuditReservation ID from the query.
// Returns a *NotFoundError when no RequestAuditReservation ID was found.
func (_q *RequestAuditReservationQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{requestauditreservation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RequestAuditReservationQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RequestAuditReservation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RequestAuditReservation entity is found.
// Returns a *NotFoundError when no RequestAuditReservation entities are found.
func (_q *RequestAuditReservationQuery) Only(ctx context.Context) (*RequestAuditReservation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{requestauditreservation.Label}
	default:
		return nil, &NotSingularError{requestauditreservation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RequestAuditReservationQuery) OnlyX(ctx context.Context) *RequestAuditReservation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RequestAuditReservation ID in the query.
// Returns a *NotSingularError when more than one RequestAuditReservation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RequestAuditReservationQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{requestauditreservation.Label}
	default:
		err = &NotSingularError{requestauditreservation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RequestAuditReservationQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RequestAuditReservations.
func (_q *RequestAuditReservationQuery) All(ctx context.Context) ([]*RequestAuditReservation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RequestAuditReservation, *RequestAuditReservationQuery]()
	return withInterceptors[[]*RequestAuditReservation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RequestAuditReservationQuery) AllX(ctx context.Context) []*RequestAuditReservation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RequestAuditReservation IDs.
func (_q *RequestAuditReservationQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(requestauditreservation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RequestAuditReservationQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RequestAuditReservationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RequestAuditReservationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RequestAuditReservationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RequestAuditReservationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RequestAuditReservationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RequestAuditReservationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RequestAuditReservationQuery) Clone() *RequestAuditReservationQuery {
	if _q == nil {
		return nil
	}
	return &RequestAuditReservationQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]requestauditreservation.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.RequestAuditReservation{}, _q.predicates...),
		withUsageLog: _q.withUsageLog.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUsageLog tells the query-builder to eager-load the nodes that are connected to
// the "usage_log" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RequestAuditReservationQuery) WithUsageLog(opts ...func(*UsageLogQuery)) *RequestAuditReservationQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsageLog = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LogicalKey string `json:"logical_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RequestAuditReservation.Query().
//		GroupBy(requestauditreservation.FieldLogicalKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RequestAuditReservationQuery) GroupBy(field string, fields ...string) *RequestAuditReservationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RequestAuditReservationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = requestauditreservation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LogicalKey string `json:"logical_key,omitempty"`
//	}
//
//	client.RequestAuditReservation.Query().
//		Select(requestauditreservation.FieldLogicalKey).
//		Scan(ctx, &v)
func (_q *RequestAuditReservationQuery) Select(fields ...string) *RequestAuditReservationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RequestAuditReservationSelect{RequestAuditReservationQuery: _q}
	sbuild.label = requestauditreservation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RequestAuditReservationSelect configured with the given aggregations.
func (_q *RequestAuditReservationQuery) Aggregate(fns ...AggregateFunc) *RequestAuditReservationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RequestAuditReservationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !requestauditreservation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RequestAuditReservationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RequestAuditReservation, error) {
	var (
		nodes       = []*RequestAuditReservation{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withUsageLog != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RequestAuditReservation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RequestAuditReservation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUsageLog; query != nil {
		if err := _q.loadUsageLog(ctx, query, nodes, nil,
			func(n *RequestAuditReservation, e *UsageLog) { n.Edges.UsageLog = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RequestAuditReservationQuery) loadUsageLog(ctx context.Context, query *UsageLogQuery, nodes []*RequestAuditReservation, init func(*RequestAuditReservation), assign func(*RequestAuditReservation, *UsageLog)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RequestAuditReservation)
	for i := range nodes {
		if nodes[i].UsageLogID == nil {
			continue
		}
		fk := *nodes[i].UsageLogID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usagelog.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "usage_log_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RequestAuditReservationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RequestAuditReservationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(requestauditreservation.Table, requestauditreservation.Columns, sqlgraph.NewFieldSpec(requestauditreservation.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestauditreservation.FieldID)
		for i := range fields {
			if fields[i] != requestauditreservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUsageLog != nil {
			_spec.Node.AddColumnOnce(requestauditreservation.FieldUsageLogID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RequestAuditReservationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(requestauditreservation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = requestauditreservation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RequestAuditReservationQuery) ForUpdate(opts ...sql.LockOption) *RequestAuditReservationQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RequestAuditReservationQuery) ForShare(opts ...sql.LockOption) *RequestAuditReservationQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RequestAuditReservationGroupBy is the group-by builder for RequestAuditReservation entities.
type RequestAuditReservationGroupBy struct {
	selector
	build *RequestAuditReservationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RequestAuditReservationGroupBy) Aggregate(fns ...AggregateFunc) *RequestAuditReservationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RequestAuditReservationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RequestAuditReservationQuery, *RequestAuditReservationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RequestAuditReservationGroupBy) sqlScan(ctx context.Context, root *RequestAuditReservationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RequestAuditReservationSelect is the builder for selecting fields of RequestAuditReservation entities.
type RequestAuditReservationSelect struct {
	*RequestAuditReservationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RequestAuditReservationSelect) Aggregate(fns ...AggregateFunc) *RequestAuditReservationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RequestAuditReservationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RequestAuditReservationQuery, *RequestAuditReservationSelect](ctx, _s.RequestAuditReservationQuery, _s, _s.inters, v)
}

func (_s *RequestAuditReservationSelect) sqlScan(ctx context.Context, root *RequestAuditReservationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
