// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestauditreservation"
)

// RequestAuditReservationDelete is the builder for deleting a RequestAuditReservation entity.
type RequestAuditReservationDelete struct {
	config
	hooks    []Hook
	mutation *RequestAuditReservationMutation
}

// Where appends a list predicates to the RequestAuditReservationDelete builder.
func (_d *RequestAuditReservationDelete) Where(ps ...predicate.RequestAuditReservation) *RequestAuditReservationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RequestAuditReservationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestAuditReservationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RequestAuditReservationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(requestauditreservation.Table, sqlgraph.NewFieldSpec(requestauditreservation.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RequestAuditReservationDeleteOne is the builder for deleting a single RequestAuditReservation entity.
type RequestAuditReservationDeleteOne struct {
	_d *RequestAuditReservationDelete
}

// Where appends a list predicates to the RequestAuditReservationDelete builder.
func (_d *RequestAuditReservationDeleteOne) Where(ps ...predicate.RequestAuditReservation) *RequestAuditReservationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RequestAuditReservationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{requestauditreservation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestAuditReservationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
