// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/requestaudit"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// RequestAudit is the model entity for the RequestAudit schema.
type RequestAudit struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int64 `json:"usage_log_id,omitempty"`
	// Allowed protocol headers only; credentials stored as presence
	Headers map[string]interface{} `json:"headers,omitempty"`
	// SSE event skeletons; never stores event text or deltas
	Events []map[string]interface{} `json:"events,omitempty"`
	// Upstream attempt timeline; never stores model body
	Attempts []map[string]interface{} `json:"attempts,omitempty"`
	// 采集完整性: complete, truncated, incomplete, not_captured
	CaptureCompleteness string `json:"capture_completeness,omitempty"`
	// 采集原因码；phase1_uncovered 表示第一阶段未覆盖
	CaptureReason string `json:"capture_reason,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint *string `json:"request_fingerprint,omitempty"`
	// FingerprintKeyVersion holds the value of the "fingerprint_key_version" field.
	FingerprintKeyVersion int `json:"fingerprint_key_version,omitempty"`
	// Internal per-record random salt; never exposed in audit DTOs
	FingerprintSalt *[]byte `json:"-"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestAuditQuery when eager-loading is set.
	Edges        RequestAuditEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestAuditEdges holds the relations/edges for other nodes in the graph.
type RequestAuditEdges struct {
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestAuditEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestAudit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestaudit.FieldHeaders, requestaudit.FieldEvents, requestaudit.FieldAttempts, requestaudit.FieldFingerprintSalt, requestaudit.FieldMetadata:
			values[i] = new([]byte)
		case requestaudit.FieldID, requestaudit.FieldUsageLogID, requestaudit.FieldFingerprintKeyVersion:
			values[i] = new(sql.NullInt64)
		case requestaudit.FieldCaptureCompleteness, requestaudit.FieldCaptureReason, requestaudit.FieldRequestFingerprint:
			values[i] = new(sql.NullString)
		case requestaudit.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestAudit fields.
func (_m *RequestAudit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestaudit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case requestaudit.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = value.Int64
			}
		case requestaudit.FieldHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Headers); err != nil {
					return fmt.Errorf("unmarshal field headers: %w", err)
				}
			}
		case requestaudit.FieldEvents:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field events", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Events); err != nil {
					return fmt.Errorf("unmarshal field events: %w", err)
				}
			}
		case requestaudit.FieldAttempts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Attempts); err != nil {
					return fmt.Errorf("unmarshal field attempts: %w", err)
				}
			}
		case requestaudit.FieldCaptureCompleteness:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capture_completeness", values[i])
			} else if value.Valid {
				_m.CaptureCompleteness = value.String
			}
		case requestaudit.FieldCaptureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capture_reason", values[i])
			} else if value.Valid {
				_m.CaptureReason = value.String
			}
		case requestaudit.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = new(string)
				*_m.RequestFingerprint = value.String
			}
		case requestaudit.FieldFingerprintKeyVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint_key_version", values[i])
			} else if value.Valid {
				_m.FingerprintKeyVersion = int(value.Int64)
			}
		case requestaudit.FieldFingerprintSalt:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint_salt", values[i])
			} else if value != nil {
				_m.FingerprintSalt = value
			}
		case requestaudit.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case requestaudit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestAudit.
// This includes values selected through modifiers, order, etc.
func (_m *RequestAudit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsageLog queries the "usage_log" edge of the RequestAudit entity.
func (_m *RequestAudit) QueryUsageLog() *UsageLogQuery {
	return NewRequestAuditClient(_m.config).QueryUsageLog(_m)
}

// Update returns a builder for updating this RequestAudit.
// Note that you need to call RequestAudit.Unwrap() before calling this method if this RequestAudit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestAudit) Update() *RequestAuditUpdateOne {
	return NewRequestAuditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestAudit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestAudit) Unwrap() *RequestAudit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestAudit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestAudit) String() string {
	var builder strings.Builder
	builder.WriteString("RequestAudit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Headers))
	builder.WriteString(", ")
	builder.WriteString("events=")
	builder.WriteString(fmt.Sprintf("%v", _m.Events))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("capture_completeness=")
	builder.WriteString(_m.CaptureCompleteness)
	builder.WriteString(", ")
	builder.WriteString("capture_reason=")
	builder.WriteString(_m.CaptureReason)
	builder.WriteString(", ")
	if v := _m.RequestFingerprint; v != nil {
		builder.WriteString("request_fingerprint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("fingerprint_key_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.FingerprintKeyVersion))
	builder.WriteString(", ")
	if v := _m.FingerprintSalt; v != nil {
		builder.WriteString("fingerprint_salt=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestAudits is a parsable slice of RequestAudit.
type RequestAudits []*RequestAudit
