// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/requestauditreservation"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// RequestAuditReservation is the model entity for the RequestAuditReservation schema.
type RequestAuditReservation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// LogicalKey holds the value of the "logical_key" field.
	LogicalKey string `json:"logical_key,omitempty"`
	// RouteFamily holds the value of the "route_family" field.
	RouteFamily string `json:"route_family,omitempty"`
	// Forced holds the value of the "forced" field.
	Forced bool `json:"forced,omitempty"`
	// Sanitized protocol headers; never stores credential plaintext
	Headers map[string]interface{} `json:"headers,omitempty"`
	// Reserved upstream attempt metadata; never stores model body
	Attempts []map[string]interface{} `json:"attempts,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// CaptureCompleteness holds the value of the "capture_completeness" field.
	CaptureCompleteness string `json:"capture_completeness,omitempty"`
	// CaptureReason holds the value of the "capture_reason" field.
	CaptureReason string `json:"capture_reason,omitempty"`
	// SendStartedAt holds the value of the "send_started_at" field.
	SendStartedAt *time.Time `json:"send_started_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestAuditReservationQuery when eager-loading is set.
	Edges        RequestAuditReservationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestAuditReservationEdges holds the relations/edges for other nodes in the graph.
type RequestAuditReservationEdges struct {
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestAuditReservationEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestAuditReservation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestauditreservation.FieldHeaders, requestauditreservation.FieldAttempts:
			values[i] = new([]byte)
		case requestauditreservation.FieldForced:
			values[i] = new(sql.NullBool)
		case requestauditreservation.FieldID, requestauditreservation.FieldUsageLogID:
			values[i] = new(sql.NullInt64)
		case requestauditreservation.FieldLogicalKey, requestauditreservation.FieldRouteFamily, requestauditreservation.FieldCaptureCompleteness, requestauditreservation.FieldCaptureReason:
			values[i] = new(sql.NullString)
		case requestauditreservation.FieldSendStartedAt, requestauditreservation.FieldExpiresAt, requestauditreservation.FieldCreatedAt, requestauditreservation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestAuditReservation fields.
func (_m *RequestAuditReservation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestauditreservation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case requestauditreservation.FieldLogicalKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logical_key", values[i])
			} else if value.Valid {
				_m.LogicalKey = value.String
			}
		case requestauditreservation.FieldRouteFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_family", values[i])
			} else if value.Valid {
				_m.RouteFamily = value.String
			}
		case requestauditreservation.FieldForced:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field forced", values[i])
			} else if value.Valid {
				_m.Forced = value.Bool
			}
		case requestauditreservation.FieldHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Headers); err != nil {
					return fmt.Errorf("unmarshal field headers: %w", err)
				}
			}
		case requestauditreservation.FieldAttempts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Attempts); err != nil {
					return fmt.Errorf("unmarshal field attempts: %w", err)
				}
			}
		case requestauditreservation.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case requestauditreservation.FieldCaptureCompleteness:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capture_completeness", values[i])
			} else if value.Valid {
				_m.CaptureCompleteness = value.String
			}
		case requestauditreservation.FieldCaptureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capture_reason", values[i])
			} else if value.Valid {
				_m.CaptureReason = value.String
			}
		case requestauditreservation.FieldSendStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field send_started_at", values[i])
			} else if value.Valid {
				_m.SendStartedAt = new(time.Time)
				*_m.SendStartedAt = value.Time
			}
		case requestauditreservation.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case requestauditreservation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case requestauditreservation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestAuditReservation.
// This includes values selected through modifiers, order, etc.
func (_m *RequestAuditReservation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsageLog queries the "usage_log" edge of the RequestAuditReservation entity.
func (_m *RequestAuditReservation) QueryUsageLog() *UsageLogQuery {
	return NewRequestAuditReservationClient(_m.config).QueryUsageLog(_m)
}

// Update returns a builder for updating this RequestAuditReservation.
// Note that you need to call RequestAuditReservation.Unwrap() before calling this method if this RequestAuditReservation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestAuditReservation) Update() *RequestAuditReservationUpdateOne {
	return NewRequestAuditReservationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestAuditReservation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestAuditReservation) Unwrap() *RequestAuditReservation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestAuditReservation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestAuditReservation) String() string {
	var builder strings.Builder
	builder.WriteString("RequestAuditReservation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("logical_key=")
	builder.WriteString(_m.LogicalKey)
	builder.WriteString(", ")
	builder.WriteString("route_family=")
	builder.WriteString(_m.RouteFamily)
	builder.WriteString(", ")
	builder.WriteString("forced=")
	builder.WriteString(fmt.Sprintf("%v", _m.Forced))
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Headers))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("capture_completeness=")
	builder.WriteString(_m.CaptureCompleteness)
	builder.WriteString(", ")
	builder.WriteString("capture_reason=")
	builder.WriteString(_m.CaptureReason)
	builder.WriteString(", ")
	if v := _m.SendStartedAt; v != nil {
		builder.WriteString("send_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestAuditReservations is a parsable slice of RequestAuditReservation.
type RequestAuditReservations []*RequestAuditReservation
