// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestauditreservation"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// RequestAuditReservationUpdate is the builder for updating RequestAuditReservation entities.
type RequestAuditReservationUpdate struct {
	config
	hooks    []Hook
	mutation *RequestAuditReservationMutation
}

// Where appends a list predicates to the RequestAuditReservationUpdate builder.
func (_u *RequestAuditReservationUpdate) Where(ps ...predicate.RequestAuditReservation) *RequestAuditReservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLogicalKey sets the "logical_key" field.
func (_u *RequestAuditReservationUpdate) SetLogicalKey(v string) *RequestAuditReservationUpdate {
	_u.mutation.SetLogicalKey(v)
	return _u
}

// SetNillableLogicalKey sets the "logical_key" field if the given value is not nil.
func (_u *RequestAuditReservationUpdate) SetNillableLogicalKey(v *string) *RequestAuditReservationUpdate {
	if v != nil {
		_u.SetLogicalKey(*v)
	}
	return _u
}

// SetRouteFamily sets the "route_family" field.
func (_u *RequestAuditReservationUpdate) SetRouteFamily(v string) *RequestAuditReservationUpdate {
	_u.mutation.SetRouteFamily(v)
	return _u
}

// SetNillableRouteFamily sets the "route_family" field if the given value is not nil.
func (_u *RequestAuditReservationUpdate) SetNillableRouteFamily(v *string) *RequestAuditReservationUpdate {
	if v != nil {
		_u.SetRouteFamily(*v)
	}
	return _u
}

// SetForced sets the "forced" field.
func (_u *RequestAuditReservationUpdate) SetForced(v bool) *RequestAuditReservationUpdate {
	_u.mutation.SetForced(v)
	return _u
}

// SetNillableForced sets the "forced" field if the given value is not nil.
func (_u *RequestAuditReservationUpdate) SetNillableForced(v *bool) *RequestAuditReservationUpdate {
	if v != nil {
		_u.SetForced(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *RequestAuditReservationUpdate) SetHeaders(v map[string]interface{}) *RequestAuditReservationUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *RequestAuditReservationUpdate) SetAttempts(v []map[string]interface{}) *RequestAuditReservationUpdate {
	_u.mutation.SetAttempts(v)
	return _u
}

// AppendAttempts appends value to the "attempts" field.
func (_u *RequestAuditReservationUpdate) AppendAttempts(v []map[string]interface{}) *RequestAuditReservationUpdate {
	_u.mutation.AppendAttempts(v)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *RequestAuditReservationUpdate) SetUsageLogID(v int64) *RequestAuditReservationUpdate {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *RequestAuditReservationUpdate) SetNillableUsageLogID(v *int64) *RequestAuditReservationUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *RequestAuditReservationUpdate) ClearUsageLogID() *RequestAuditReservationUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (_u *RequestAuditReservationUpdate) SetCaptureCompleteness(v string) *RequestAuditReservationUpdate {
	_u.mutation.SetCaptureCompleteness(v)
	return _u
}

// SetNillableCaptureCompleteness sets the "capture_completeness" field if the given value is not nil.
func (_u *RequestAuditReservationUpdate) SetNillableCaptureCompleteness(v *string) *RequestAuditReservationUpdate {
	if v != nil {
		_u.SetCaptureCompleteness(*v)
	}
	return _u
}

// SetCaptureReason sets the "capture_reason" field.
func (_u *RequestAuditReservationUpdate) SetCaptureReason(v string) *RequestAuditReservationUpdate {
	_u.mutation.SetCaptureReason(v)
	return _u
}

// SetNillableCaptureReason sets the "capture_reason" field if the given value is not nil.
func (_u *RequestAuditReservationUpdate) SetNillableCaptureReason(v *string) *RequestAuditReservationUpdate {
	if v != nil {
		_u.SetCaptureReason(*v)
	}
	return _u
}

// SetSendStartedAt sets the "send_started_at" field.
func (_u *RequestAuditReservationUpdate) SetSendStartedAt(v time.Time) *RequestAuditReservationUpdate {
	_u.mutation.SetSendStartedAt(v)
	return _u
}

// SetNillableSendStartedAt sets the "send_started_at" field if the given value is not nil.
func (_u *RequestAuditReservationUpdate) SetNillableSendStartedAt(v *time.Time) *RequestAuditReservationUpdate {
	if v != nil {
		_u.SetSendStartedAt(*v)
	}
	return _u
}

// ClearSendStartedAt clears the value of the "send_started_at" field.
func (_u *RequestAuditReservationUpdate) ClearSendStartedAt() *RequestAuditReservationUpdate {
	_u.mutation.ClearSendStartedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RequestAuditReservationUpdate) SetExpiresAt(v time.Time) *RequestAuditReservationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RequestAuditReservationUpdate) SetNillableExpiresAt(v *time.Time) *RequestAuditReservationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestAuditReservationUpdate) SetUpdatedAt(v time.Time) *RequestAuditReservationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *RequestAuditReservationUpdate) SetUsageLog(v *UsageLog) *RequestAuditReservationUpdate {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the RequestAuditReservationMutation object of the builder.
func (_u *RequestAuditReservationUpdate) Mutation() *RequestAuditReservationMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *RequestAuditReservationUpdate) ClearUsageLog() *RequestAuditReservationUpdate {
	_u.mutation.ClearUsageLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestAuditReservationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestAuditReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestAuditReservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestAuditReservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestAuditReservationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestauditreservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestAuditReservationUpdate) check() error {
	if v, ok := _u.mutation.LogicalKey(); ok {
		if err := requestauditreservation.LogicalKeyValidator(v); err != nil {
			return &ValidationError{Name: "logical_key", err: fmt.Errorf(`ent: validator failed for field "RequestAuditReservation.logical_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteFamily(); ok {
		if err := requestauditreservation.RouteFamilyValidator(v); err != nil {
			return &ValidationError{Name: "route_family", err: fmt.Errorf(`ent: validator failed for field "RequestAuditReservation.route_family": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestAuditReservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestauditreservation.Table, requestauditreservation.Columns, sqlgraph.NewFieldSpec(requestauditreservation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LogicalKey(); ok {
		_spec.SetField(requestauditreservation.FieldLogicalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteFamily(); ok {
		_spec.SetField(requestauditreservation.FieldRouteFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.Forced(); ok {
		_spec.SetField(requestauditreservation.FieldForced, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(requestauditreservation.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(requestauditreservation.FieldAttempts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttempts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestauditreservation.FieldAttempts, value)
		})
	}
	if value, ok := _u.mutation.CaptureCompleteness(); ok {
		_spec.SetField(requestauditreservation.FieldCaptureCompleteness, field.TypeString, value)
	}
	if value, ok := _u.mutation.CaptureReason(); ok {
		_spec.SetField(requestauditreservation.FieldCaptureReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.SendStartedAt(); ok {
		_spec.SetField(requestauditreservation.FieldSendStartedAt, field.TypeTime, value)
	}
	if _u.mutation.SendStartedAtCleared() {
		_spec.ClearField(requestauditreservation.FieldSendStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(requestauditreservation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestauditreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestauditreservation.UsageLogTable,
			Columns: []string{requestauditreservation.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestauditreservation.UsageLogTable,
			Columns: []string{requestauditreservation.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestauditreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestAuditReservationUpdateOne is the builder for updating a single RequestAuditReservation entity.
type RequestAuditReservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestAuditReservationMutation
}

// SetLogicalKey sets the "logical_key" field.
func (_u *RequestAuditReservationUpdateOne) SetLogicalKey(v string) *RequestAuditReservationUpdateOne {
	_u.mutation.SetLogicalKey(v)
	return _u
}

// SetNillableLogicalKey sets the "logical_key" field if the given value is not nil.
func (_u *RequestAuditReservationUpdateOne) SetNillableLogicalKey(v *string) *RequestAuditReservationUpdateOne {
	if v != nil {
		_u.SetLogicalKey(*v)
	}
	return _u
}

// SetRouteFamily sets the "route_family" field.
func (_u *RequestAuditReservationUpdateOne) SetRouteFamily(v string) *RequestAuditReservationUpdateOne {
	_u.mutation.SetRouteFamily(v)
	return _u
}

// SetNillableRouteFamily sets the "route_family" field if the given value is not nil.
func (_u *RequestAuditReservationUpdateOne) SetNillableRouteFamily(v *string) *RequestAuditReservationUpdateOne {
	if v != nil {
		_u.SetRouteFamily(*v)
	}
	return _u
}

// SetForced sets the "forced" field.
func (_u *RequestAuditReservationUpdateOne) SetForced(v bool) *RequestAuditReservationUpdateOne {
	_u.mutation.SetForced(v)
	return _u
}

// SetNillableForced sets the "forced" field if the given value is not nil.
func (_u *RequestAuditReservationUpdateOne) SetNillableForced(v *bool) *RequestAuditReservationUpdateOne {
	if v != nil {
		_u.SetForced(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *RequestAuditReservationUpdateOne) SetHeaders(v map[string]interface{}) *RequestAuditReservationUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *RequestAuditReservationUpdateOne) SetAttempts(v []map[string]interface{}) *RequestAuditReservationUpdateOne {
	_u.mutation.SetAttempts(v)
	return _u
}

// AppendAttempts appends value to the "attempts" field.
func (_u *RequestAuditReservationUpdateOne) AppendAttempts(v []map[string]interface{}) *RequestAuditReservationUpdateOne {
	_u.mutation.AppendAttempts(v)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *RequestAuditReservationUpdateOne) SetUsageLogID(v int64) *RequestAuditReservationUpdateOne {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *RequestAuditReservationUpdateOne) SetNillableUsageLogID(v *int64) *RequestAuditReservationUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *RequestAuditReservationUpdateOne) ClearUsageLogID() *RequestAuditReservationUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetCaptureCompleteness sets the "capture_completeness" field.
func (_u *RequestAuditReservationUpdateOne) SetCaptureCompleteness(v string) *RequestAuditReservationUpdateOne {
	_u.mutation.SetCaptureCompleteness(v)
	return _u
}

// SetNillableCaptureCompleteness sets the "capture_completeness" field if the given value is not nil.
func (_u *RequestAuditReservationUpdateOne) SetNillableCaptureCompleteness(v *string) *RequestAuditReservationUpdateOne {
	if v != nil {
		_u.SetCaptureCompleteness(*v)
	}
	return _u
}

// SetCaptureReason sets the "capture_reason" field.
func (_u *RequestAuditReservationUpdateOne) SetCaptureReason(v string) *RequestAuditReservationUpdateOne {
	_u.mutation.SetCaptureReason(v)
	return _u
}

// SetNillableCaptureReason sets the "capture_reason" field if the given value is not nil.
func (_u *RequestAuditReservationUpdateOne) SetNillableCaptureReason(v *string) *RequestAuditReservationUpdateOne {
	if v != nil {
		_u.SetCaptureReason(*v)
	}
	return _u
}

// SetSendStartedAt sets the "send_started_at" field.
func (_u *RequestAuditReservationUpdateOne) SetSendStartedAt(v time.Time) *RequestAuditReservationUpdateOne {
	_u.mutation.SetSendStartedAt(v)
	return _u
}

// SetNillableSendStartedAt sets the "send_started_at" field if the given value is not nil.
func (_u *RequestAuditReservationUpdateOne) SetNillableSendStartedAt(v *time.Time) *RequestAuditReservationUpdateOne {
	if v != nil {
		_u.SetSendStartedAt(*v)
	}
	return _u
}

// ClearSendStartedAt clears the value of the "send_started_at" field.
func (_u *RequestAuditReservationUpdateOne) ClearSendStartedAt() *RequestAuditReservationUpdateOne {
	_u.mutation.ClearSendStartedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RequestAuditReservationUpdateOne) SetExpiresAt(v time.Time) *RequestAuditReservationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RequestAuditReservationUpdateOne) SetNillableExpiresAt(v *time.Time) *RequestAuditReservationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestAuditReservationUpdateOne) SetUpdatedAt(v time.Time) *RequestAuditReservationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *RequestAuditReservationUpdateOne) SetUsageLog(v *UsageLog) *RequestAuditReservationUpdateOne {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the RequestAuditReservationMutation object of the builder.
func (_u *RequestAuditReservationUpdateOne) Mutation() *RequestAuditReservationMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *RequestAuditReservationUpdateOne) ClearUsageLog() *RequestAuditReservationUpdateOne {
	_u.mutation.ClearUsageLog()
	return _u
}

// Where appends a list predicates to the RequestAuditReservationUpdate builder.
func (_u *RequestAuditReservationUpdateOne) Where(ps ...predicate.RequestAuditReservation) *RequestAuditReservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestAuditReservationUpdateOne) Select(field string, fields ...string) *RequestAuditReservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestAuditReservation entity.
func (_u *RequestAuditReservationUpdateOne) Save(ctx context.Context) (*RequestAuditReservation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestAuditReservationUpdateOne) SaveX(ctx context.Context) *RequestAuditReservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestAuditReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestAuditReservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestAuditReservationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestauditreservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestAuditReservationUpdateOne) check() error {
	if v, ok := _u.mutation.LogicalKey(); ok {
		if err := requestauditreservation.LogicalKeyValidator(v); err != nil {
			return &ValidationError{Name: "logical_key", err: fmt.Errorf(`ent: validator failed for field "RequestAuditReservation.logical_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteFamily(); ok {
		if err := requestauditreservation.RouteFamilyValidator(v); err != nil {
			return &ValidationError{Name: "route_family", err: fmt.Errorf(`ent: validator failed for field "RequestAuditReservation.route_family": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestAuditReservationUpdateOne) sqlSave(ctx context.Context) (_node *RequestAuditReservation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestauditreservation.Table, requestauditreservation.Columns, sqlgraph.NewFieldSpec(requestauditreservation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestAuditReservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestauditreservation.FieldID)
		for _, f := range fields {
			if !requestauditreservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestauditreservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LogicalKey(); ok {
		_spec.SetField(requestauditreservation.FieldLogicalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteFamily(); ok {
		_spec.SetField(requestauditreservation.FieldRouteFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.Forced(); ok {
		_spec.SetField(requestauditreservation.FieldForced, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(requestauditreservation.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(requestauditreservation.FieldAttempts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttempts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestauditreservation.FieldAttempts, value)
		})
	}
	if value, ok := _u.mutation.CaptureCompleteness(); ok {
		_spec.SetField(requestauditreservation.FieldCaptureCompleteness, field.TypeString, value)
	}
	if value, ok := _u.mutation.CaptureReason(); ok {
		_spec.SetField(requestauditreservation.FieldCaptureReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.SendStartedAt(); ok {
		_spec.SetField(requestauditreservation.FieldSendStartedAt, field.TypeTime, value)
	}
	if _u.mutation.SendStartedAtCleared() {
		_spec.ClearField(requestauditreservation.FieldSendStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(requestauditreservation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestauditreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestauditreservation.UsageLogTable,
			Columns: []string{requestauditreservation.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   requestauditreservation.UsageLogTable,
			Columns: []string{requestauditreservation.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RequestAuditReservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestauditreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
