// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/uservisibleaccount"
)

// UserVisibleAccountCreate is the builder for creating a UserVisibleAccount entity.
type UserVisibleAccountCreate struct {
	config
	mutation *UserVisibleAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserVisibleAccountCreate) SetUserID(v int64) *UserVisibleAccountCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UserVisibleAccountCreate) SetAccountID(v int64) *UserVisibleAccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGrantedBy sets the "granted_by" field.
func (_c *UserVisibleAccountCreate) SetGrantedBy(v int64) *UserVisibleAccountCreate {
	_c.mutation.SetGrantedBy(v)
	return _c
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_c *UserVisibleAccountCreate) SetNillableGrantedBy(v *int64) *UserVisibleAccountCreate {
	if v != nil {
		_c.SetGrantedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserVisibleAccountCreate) SetCreatedAt(v time.Time) *UserVisibleAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserVisibleAccountCreate) SetNillableCreatedAt(v *time.Time) *UserVisibleAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserVisibleAccountCreate) SetUser(v *User) *UserVisibleAccountCreate {
	return _c.SetUserID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *UserVisibleAccountCreate) SetAccount(v *Account) *UserVisibleAccountCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the UserVisibleAccountMutation object of the builder.
func (_c *UserVisibleAccountCreate) Mutation() *UserVisibleAccountMutation {
	return _c.mutation
}

// Save creates the UserVisibleAccount in the database.
func (_c *UserVisibleAccountCreate) Save(ctx context.Context) (*UserVisibleAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserVisibleAccountCreate) SaveX(ctx context.Context) *UserVisibleAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserVisibleAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserVisibleAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserVisibleAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uservisibleaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserVisibleAccountCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserVisibleAccount.user_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "UserVisibleAccount.account_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserVisibleAccount.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserVisibleAccount.user"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "UserVisibleAccount.account"`)}
	}
	return nil
}

func (_c *UserVisibleAccountCreate) sqlSave(ctx context.Context) (*UserVisibleAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *UserVisibleAccountCreate) createSpec() (*UserVisibleAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &UserVisibleAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uservisibleaccount.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GrantedBy(); ok {
		_spec.SetField(uservisibleaccount.FieldGrantedBy, field.TypeInt64, value)
		_node.GrantedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uservisibleaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.UserTable,
			Columns: []string{uservisibleaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.AccountTable,
			Columns: []string{uservisibleaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserVisibleAccount.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserVisibleAccountUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserVisibleAccountCreate) OnConflict(opts ...sql.ConflictOption) *UserVisibleAccountUpsertOne {
	_c.conflict = opts
	return &UserVisibleAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserVisibleAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserVisibleAccountCreate) OnConflictColumns(columns ...string) *UserVisibleAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserVisibleAccountUpsertOne{
		create: _c,
	}
}

type (
	// UserVisibleAccountUpsertOne is the builder for "upsert"-ing
	//  one UserVisibleAccount node.
	UserVisibleAccountUpsertOne struct {
		create *UserVisibleAccountCreate
	}

	// UserVisibleAccountUpsert is the "OnConflict" setter.
	UserVisibleAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserVisibleAccountUpsert) SetUserID(v int64) *UserVisibleAccountUpsert {
	u.Set(uservisibleaccount.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserVisibleAccountUpsert) UpdateUserID() *UserVisibleAccountUpsert {
	u.SetExcluded(uservisibleaccount.FieldUserID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UserVisibleAccountUpsert) SetAccountID(v int64) *UserVisibleAccountUpsert {
	u.Set(uservisibleaccount.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UserVisibleAccountUpsert) UpdateAccountID() *UserVisibleAccountUpsert {
	u.SetExcluded(uservisibleaccount.FieldAccountID)
	return u
}

// SetGrantedBy sets the "granted_by" field.
func (u *UserVisibleAccountUpsert) SetGrantedBy(v int64) *UserVisibleAccountUpsert {
	u.Set(uservisibleaccount.FieldGrantedBy, v)
	return u
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *UserVisibleAccountUpsert) UpdateGrantedBy() *UserVisibleAccountUpsert {
	u.SetExcluded(uservisibleaccount.FieldGrantedBy)
	return u
}

// AddGrantedBy adds v to the "granted_by" field.
func (u *UserVisibleAccountUpsert) AddGrantedBy(v int64) *UserVisibleAccountUpsert {
	u.Add(uservisibleaccount.FieldGrantedBy, v)
	return u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (u *UserVisibleAccountUpsert) ClearGrantedBy() *UserVisibleAccountUpsert {
	u.SetNull(uservisibleaccount.FieldGrantedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserVisibleAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserVisibleAccountUpsertOne) UpdateNewValues() *UserVisibleAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uservisibleaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserVisibleAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserVisibleAccountUpsertOne) Ignore() *UserVisibleAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserVisibleAccountUpsertOne) DoNothing() *UserVisibleAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserVisibleAccountCreate.OnConflict
// documentation for more info.
func (u *UserVisibleAccountUpsertOne) Update(set func(*UserVisibleAccountUpsert)) *UserVisibleAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserVisibleAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserVisibleAccountUpsertOne) SetUserID(v int64) *UserVisibleAccountUpsertOne {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserVisibleAccountUpsertOne) UpdateUserID() *UserVisibleAccountUpsertOne {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UserVisibleAccountUpsertOne) SetAccountID(v int64) *UserVisibleAccountUpsertOne {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UserVisibleAccountUpsertOne) UpdateAccountID() *UserVisibleAccountUpsertOne {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetGrantedBy sets the "granted_by" field.
func (u *UserVisibleAccountUpsertOne) SetGrantedBy(v int64) *UserVisibleAccountUpsertOne {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.SetGrantedBy(v)
	})
}

// AddGrantedBy adds v to the "granted_by" field.
func (u *UserVisibleAccountUpsertOne) AddGrantedBy(v int64) *UserVisibleAccountUpsertOne {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.AddGrantedBy(v)
	})
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *UserVisibleAccountUpsertOne) UpdateGrantedBy() *UserVisibleAccountUpsertOne {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.UpdateGrantedBy()
	})
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (u *UserVisibleAccountUpsertOne) ClearGrantedBy() *UserVisibleAccountUpsertOne {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.ClearGrantedBy()
	})
}

// Exec executes the query.
func (u *UserVisibleAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserVisibleAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserVisibleAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// UserVisibleAccountCreateBulk is the builder for creating many UserVisibleAccount entities in bulk.
type UserVisibleAccountCreateBulk struct {
	config
	err      error
	builders []*UserVisibleAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the UserVisibleAccount entities in the database.
func (_c *UserVisibleAccountCreateBulk) Save(ctx context.Context) ([]*UserVisibleAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserVisibleAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserVisibleAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserVisibleAccountCreateBulk) SaveX(ctx context.Context) []*UserVisibleAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserVisibleAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserVisibleAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserVisibleAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserVisibleAccountUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserVisibleAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserVisibleAccountUpsertBulk {
	_c.conflict = opts
	return &UserVisibleAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserVisibleAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserVisibleAccountCreateBulk) OnConflictColumns(columns ...string) *UserVisibleAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserVisibleAccountUpsertBulk{
		create: _c,
	}
}

// UserVisibleAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of UserVisibleAccount nodes.
type UserVisibleAccountUpsertBulk struct {
	create *UserVisibleAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserVisibleAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserVisibleAccountUpsertBulk) UpdateNewValues() *UserVisibleAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uservisibleaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserVisibleAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserVisibleAccountUpsertBulk) Ignore() *UserVisibleAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserVisibleAccountUpsertBulk) DoNothing() *UserVisibleAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserVisibleAccountCreateBulk.OnConflict
// documentation for more info.
func (u *UserVisibleAccountUpsertBulk) Update(set func(*UserVisibleAccountUpsert)) *UserVisibleAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserVisibleAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserVisibleAccountUpsertBulk) SetUserID(v int64) *UserVisibleAccountUpsertBulk {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserVisibleAccountUpsertBulk) UpdateUserID() *UserVisibleAccountUpsertBulk {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UserVisibleAccountUpsertBulk) SetAccountID(v int64) *UserVisibleAccountUpsertBulk {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UserVisibleAccountUpsertBulk) UpdateAccountID() *UserVisibleAccountUpsertBulk {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetGrantedBy sets the "granted_by" field.
func (u *UserVisibleAccountUpsertBulk) SetGrantedBy(v int64) *UserVisibleAccountUpsertBulk {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.SetGrantedBy(v)
	})
}

// AddGrantedBy adds v to the "granted_by" field.
func (u *UserVisibleAccountUpsertBulk) AddGrantedBy(v int64) *UserVisibleAccountUpsertBulk {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.AddGrantedBy(v)
	})
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *UserVisibleAccountUpsertBulk) UpdateGrantedBy() *UserVisibleAccountUpsertBulk {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.UpdateGrantedBy()
	})
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (u *UserVisibleAccountUpsertBulk) ClearGrantedBy() *UserVisibleAccountUpsertBulk {
	return u.Update(func(s *UserVisibleAccountUpsert) {
		s.ClearGrantedBy()
	})
}

// Exec executes the query.
func (u *UserVisibleAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserVisibleAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserVisibleAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserVisibleAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
