// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/uservisibleaccount"
)

// UserVisibleAccountUpdate is the builder for updating UserVisibleAccount entities.
type UserVisibleAccountUpdate struct {
	config
	hooks    []Hook
	mutation *UserVisibleAccountMutation
}

// Where appends a list predicates to the UserVisibleAccountUpdate builder.
func (_u *UserVisibleAccountUpdate) Where(ps ...predicate.UserVisibleAccount) *UserVisibleAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserVisibleAccountUpdate) SetUserID(v int64) *UserVisibleAccountUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserVisibleAccountUpdate) SetNillableUserID(v *int64) *UserVisibleAccountUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UserVisibleAccountUpdate) SetAccountID(v int64) *UserVisibleAccountUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UserVisibleAccountUpdate) SetNillableAccountID(v *int64) *UserVisibleAccountUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *UserVisibleAccountUpdate) SetGrantedBy(v int64) *UserVisibleAccountUpdate {
	_u.mutation.ResetGrantedBy()
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *UserVisibleAccountUpdate) SetNillableGrantedBy(v *int64) *UserVisibleAccountUpdate {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// AddGrantedBy adds value to the "granted_by" field.
func (_u *UserVisibleAccountUpdate) AddGrantedBy(v int64) *UserVisibleAccountUpdate {
	_u.mutation.AddGrantedBy(v)
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *UserVisibleAccountUpdate) ClearGrantedBy() *UserVisibleAccountUpdate {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserVisibleAccountUpdate) SetUser(v *User) *UserVisibleAccountUpdate {
	return _u.SetUserID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *UserVisibleAccountUpdate) SetAccount(v *Account) *UserVisibleAccountUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the UserVisibleAccountMutation object of the builder.
func (_u *UserVisibleAccountUpdate) Mutation() *UserVisibleAccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserVisibleAccountUpdate) ClearUser() *UserVisibleAccountUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *UserVisibleAccountUpdate) ClearAccount() *UserVisibleAccountUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserVisibleAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserVisibleAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserVisibleAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserVisibleAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserVisibleAccountUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVisibleAccount.user"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVisibleAccount.account"`)
	}
	return nil
}

func (_u *UserVisibleAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uservisibleaccount.Table, uservisibleaccount.Columns, sqlgraph.NewFieldSpec(uservisibleaccount.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(uservisibleaccount.FieldAccountID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(uservisibleaccount.FieldGrantedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGrantedBy(); ok {
		_spec.AddField(uservisibleaccount.FieldGrantedBy, field.TypeInt64, value)
	}
	if _u.mutation.GrantedByCleared() {
		_spec.ClearField(uservisibleaccount.FieldGrantedBy, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.UserTable,
			Columns: []string{uservisibleaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.UserTable,
			Columns: []string{uservisibleaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.AccountTable,
			Columns: []string{uservisibleaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.AccountTable,
			Columns: []string{uservisibleaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uservisibleaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserVisibleAccountUpdateOne is the builder for updating a single UserVisibleAccount entity.
type UserVisibleAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserVisibleAccountMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserVisibleAccountUpdateOne) SetUserID(v int64) *UserVisibleAccountUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserVisibleAccountUpdateOne) SetNillableUserID(v *int64) *UserVisibleAccountUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UserVisibleAccountUpdateOne) SetAccountID(v int64) *UserVisibleAccountUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UserVisibleAccountUpdateOne) SetNillableAccountID(v *int64) *UserVisibleAccountUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *UserVisibleAccountUpdateOne) SetGrantedBy(v int64) *UserVisibleAccountUpdateOne {
	_u.mutation.ResetGrantedBy()
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *UserVisibleAccountUpdateOne) SetNillableGrantedBy(v *int64) *UserVisibleAccountUpdateOne {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// AddGrantedBy adds value to the "granted_by" field.
func (_u *UserVisibleAccountUpdateOne) AddGrantedBy(v int64) *UserVisibleAccountUpdateOne {
	_u.mutation.AddGrantedBy(v)
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *UserVisibleAccountUpdateOne) ClearGrantedBy() *UserVisibleAccountUpdateOne {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserVisibleAccountUpdateOne) SetUser(v *User) *UserVisibleAccountUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *UserVisibleAccountUpdateOne) SetAccount(v *Account) *UserVisibleAccountUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the UserVisibleAccountMutation object of the builder.
func (_u *UserVisibleAccountUpdateOne) Mutation() *UserVisibleAccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserVisibleAccountUpdateOne) ClearUser() *UserVisibleAccountUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *UserVisibleAccountUpdateOne) ClearAccount() *UserVisibleAccountUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the UserVisibleAccountUpdate builder.
func (_u *UserVisibleAccountUpdateOne) Where(ps ...predicate.UserVisibleAccount) *UserVisibleAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserVisibleAccountUpdateOne) Select(field string, fields ...string) *UserVisibleAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserVisibleAccount entity.
func (_u *UserVisibleAccountUpdateOne) Save(ctx context.Context) (*UserVisibleAccount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserVisibleAccountUpdateOne) SaveX(ctx context.Context) *UserVisibleAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserVisibleAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserVisibleAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserVisibleAccountUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVisibleAccount.user"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVisibleAccount.account"`)
	}
	return nil
}

func (_u *UserVisibleAccountUpdateOne) sqlSave(ctx context.Context) (_node *UserVisibleAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uservisibleaccount.Table, uservisibleaccount.Columns, sqlgraph.NewFieldSpec(uservisibleaccount.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(uservisibleaccount.FieldAccountID, field.TypeInt64))
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "UserVisibleAccount.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "UserVisibleAccount.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !uservisibleaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(uservisibleaccount.FieldGrantedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGrantedBy(); ok {
		_spec.AddField(uservisibleaccount.FieldGrantedBy, field.TypeInt64, value)
	}
	if _u.mutation.GrantedByCleared() {
		_spec.ClearField(uservisibleaccount.FieldGrantedBy, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.UserTable,
			Columns: []string{uservisibleaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.UserTable,
			Columns: []string{uservisibleaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.AccountTable,
			Columns: []string{uservisibleaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservisibleaccount.AccountTable,
			Columns: []string{uservisibleaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserVisibleAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uservisibleaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
