// Code generated by ent, DO NOT EDIT.

package requestaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the requestaudit type in the database.
	Label = "request_audit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldEvents holds the string denoting the events field in the database.
	FieldEvents = "events"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldCaptureCompleteness holds the string denoting the capture_completeness field in the database.
	FieldCaptureCompleteness = "capture_completeness"
	// FieldCaptureReason holds the string denoting the capture_reason field in the database.
	FieldCaptureReason = "capture_reason"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldFingerprintKeyVersion holds the string denoting the fingerprint_key_version field in the database.
	FieldFingerprintKeyVersion = "fingerprint_key_version"
	// FieldFingerprintSalt holds the string denoting the fingerprint_salt field in the database.
	FieldFingerprintSalt = "fingerprint_salt"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUsageLog holds the string denoting the usage_log edge name in mutations.
	EdgeUsageLog = "usage_log"
	// Table holds the table name of the requestaudit in the database.
	Table = "request_audits"
	// UsageLogTable is the table that holds the usage_log relation/edge.
	UsageLogTable = "request_audits"
	// UsageLogInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogInverseTable = "usage_logs"
	// UsageLogColumn is the table column denoting the usage_log relation/edge.
	UsageLogColumn = "usage_log_id"
)

// Columns holds all SQL columns for requestaudit fields.
var Columns = []string{
	FieldID,
	FieldUsageLogID,
	FieldHeaders,
	FieldEvents,
	FieldAttempts,
	FieldCaptureCompleteness,
	FieldCaptureReason,
	FieldRequestFingerprint,
	FieldFingerprintKeyVersion,
	FieldFingerprintSalt,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultHeaders holds the default value on creation for the "headers" field.
	DefaultHeaders map[string]interface{}
	// DefaultEvents holds the default value on creation for the "events" field.
	DefaultEvents []map[string]interface{}
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts []map[string]interface{}
	// DefaultCaptureCompleteness holds the default value on creation for the "capture_completeness" field.
	DefaultCaptureCompleteness string
	// DefaultCaptureReason holds the default value on creation for the "capture_reason" field.
	DefaultCaptureReason string
	// DefaultFingerprintKeyVersion holds the default value on creation for the "fingerprint_key_version" field.
	DefaultFingerprintKeyVersion int
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RequestAudit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByCaptureCompleteness orders the results by the capture_completeness field.
func ByCaptureCompleteness(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaptureCompleteness, opts...).ToFunc()
}

// ByCaptureReason orders the results by the capture_reason field.
func ByCaptureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaptureReason, opts...).ToFunc()
}

// ByRequestFingerprint orders the results by the request_fingerprint field.
func ByRequestFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestFingerprint, opts...).ToFunc()
}

// ByFingerprintKeyVersion orders the results by the fingerprint_key_version field.
func ByFingerprintKeyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprintKeyVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUsageLogField orders the results by usage_log field.
func ByUsageLogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogStep(), sql.OrderByField(field, opts...))
	}
}
func newUsageLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
	)
}
