// Code generated by ent, DO NOT EDIT.

package requestaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLTE(FieldID, id))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldUsageLogID, v))
}

// CaptureCompleteness applies equality check predicate on the "capture_completeness" field. It's identical to CaptureCompletenessEQ.
func CaptureCompleteness(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldCaptureCompleteness, v))
}

// CaptureReason applies equality check predicate on the "capture_reason" field. It's identical to CaptureReasonEQ.
func CaptureReason(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldCaptureReason, v))
}

// RequestFingerprint applies equality check predicate on the "request_fingerprint" field. It's identical to RequestFingerprintEQ.
func RequestFingerprint(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldRequestFingerprint, v))
}

// FingerprintKeyVersion applies equality check predicate on the "fingerprint_key_version" field. It's identical to FingerprintKeyVersionEQ.
func FingerprintKeyVersion(v int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldFingerprintKeyVersion, v))
}

// FingerprintSalt applies equality check predicate on the "fingerprint_salt" field. It's identical to FingerprintSaltEQ.
func FingerprintSalt(v []byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldFingerprintSalt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// CaptureCompletenessEQ applies the EQ predicate on the "capture_completeness" field.
func CaptureCompletenessEQ(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldCaptureCompleteness, v))
}

// CaptureCompletenessNEQ applies the NEQ predicate on the "capture_completeness" field.
func CaptureCompletenessNEQ(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNEQ(FieldCaptureCompleteness, v))
}

// CaptureCompletenessIn applies the In predicate on the "capture_completeness" field.
func CaptureCompletenessIn(vs ...string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIn(FieldCaptureCompleteness, vs...))
}

// CaptureCompletenessNotIn applies the NotIn predicate on the "capture_completeness" field.
func CaptureCompletenessNotIn(vs ...string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotIn(FieldCaptureCompleteness, vs...))
}

// CaptureCompletenessGT applies the GT predicate on the "capture_completeness" field.
func CaptureCompletenessGT(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGT(FieldCaptureCompleteness, v))
}

// CaptureCompletenessGTE applies the GTE predicate on the "capture_completeness" field.
func CaptureCompletenessGTE(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGTE(FieldCaptureCompleteness, v))
}

// CaptureCompletenessLT applies the LT predicate on the "capture_completeness" field.
func CaptureCompletenessLT(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLT(FieldCaptureCompleteness, v))
}

// CaptureCompletenessLTE applies the LTE predicate on the "capture_completeness" field.
func CaptureCompletenessLTE(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLTE(FieldCaptureCompleteness, v))
}

// CaptureCompletenessContains applies the Contains predicate on the "capture_completeness" field.
func CaptureCompletenessContains(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldContains(FieldCaptureCompleteness, v))
}

// CaptureCompletenessHasPrefix applies the HasPrefix predicate on the "capture_completeness" field.
func CaptureCompletenessHasPrefix(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldHasPrefix(FieldCaptureCompleteness, v))
}

// CaptureCompletenessHasSuffix applies the HasSuffix predicate on the "capture_completeness" field.
func CaptureCompletenessHasSuffix(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldHasSuffix(FieldCaptureCompleteness, v))
}

// CaptureCompletenessEqualFold applies the EqualFold predicate on the "capture_completeness" field.
func CaptureCompletenessEqualFold(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEqualFold(FieldCaptureCompleteness, v))
}

// CaptureCompletenessContainsFold applies the ContainsFold predicate on the "capture_completeness" field.
func CaptureCompletenessContainsFold(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldContainsFold(FieldCaptureCompleteness, v))
}

// CaptureReasonEQ applies the EQ predicate on the "capture_reason" field.
func CaptureReasonEQ(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldCaptureReason, v))
}

// CaptureReasonNEQ applies the NEQ predicate on the "capture_reason" field.
func CaptureReasonNEQ(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNEQ(FieldCaptureReason, v))
}

// CaptureReasonIn applies the In predicate on the "capture_reason" field.
func CaptureReasonIn(vs ...string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIn(FieldCaptureReason, vs...))
}

// CaptureReasonNotIn applies the NotIn predicate on the "capture_reason" field.
func CaptureReasonNotIn(vs ...string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotIn(FieldCaptureReason, vs...))
}

// CaptureReasonGT applies the GT predicate on the "capture_reason" field.
func CaptureReasonGT(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGT(FieldCaptureReason, v))
}

// CaptureReasonGTE applies the GTE predicate on the "capture_reason" field.
func CaptureReasonGTE(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGTE(FieldCaptureReason, v))
}

// CaptureReasonLT applies the LT predicate on the "capture_reason" field.
func CaptureReasonLT(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLT(FieldCaptureReason, v))
}

// CaptureReasonLTE applies the LTE predicate on the "capture_reason" field.
func CaptureReasonLTE(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLTE(FieldCaptureReason, v))
}

// CaptureReasonContains applies the Contains predicate on the "capture_reason" field.
func CaptureReasonContains(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldContains(FieldCaptureReason, v))
}

// CaptureReasonHasPrefix applies the HasPrefix predicate on the "capture_reason" field.
func CaptureReasonHasPrefix(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldHasPrefix(FieldCaptureReason, v))
}

// CaptureReasonHasSuffix applies the HasSuffix predicate on the "capture_reason" field.
func CaptureReasonHasSuffix(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldHasSuffix(FieldCaptureReason, v))
}

// CaptureReasonEqualFold applies the EqualFold predicate on the "capture_reason" field.
func CaptureReasonEqualFold(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEqualFold(FieldCaptureReason, v))
}

// CaptureReasonContainsFold applies the ContainsFold predicate on the "capture_reason" field.
func CaptureReasonContainsFold(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldContainsFold(FieldCaptureReason, v))
}

// RequestFingerprintEQ applies the EQ predicate on the "request_fingerprint" field.
func RequestFingerprintEQ(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintNEQ applies the NEQ predicate on the "request_fingerprint" field.
func RequestFingerprintNEQ(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintIn applies the In predicate on the "request_fingerprint" field.
func RequestFingerprintIn(vs ...string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintNotIn applies the NotIn predicate on the "request_fingerprint" field.
func RequestFingerprintNotIn(vs ...string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintGT applies the GT predicate on the "request_fingerprint" field.
func RequestFingerprintGT(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGT(FieldRequestFingerprint, v))
}

// RequestFingerprintGTE applies the GTE predicate on the "request_fingerprint" field.
func RequestFingerprintGTE(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGTE(FieldRequestFingerprint, v))
}

// RequestFingerprintLT applies the LT predicate on the "request_fingerprint" field.
func RequestFingerprintLT(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLT(FieldRequestFingerprint, v))
}

// RequestFingerprintLTE applies the LTE predicate on the "request_fingerprint" field.
func RequestFingerprintLTE(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLTE(FieldRequestFingerprint, v))
}

// RequestFingerprintContains applies the Contains predicate on the "request_fingerprint" field.
func RequestFingerprintContains(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldContains(FieldRequestFingerprint, v))
}

// RequestFingerprintHasPrefix applies the HasPrefix predicate on the "request_fingerprint" field.
func RequestFingerprintHasPrefix(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldHasPrefix(FieldRequestFingerprint, v))
}

// RequestFingerprintHasSuffix applies the HasSuffix predicate on the "request_fingerprint" field.
func RequestFingerprintHasSuffix(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldHasSuffix(FieldRequestFingerprint, v))
}

// RequestFingerprintIsNil applies the IsNil predicate on the "request_fingerprint" field.
func RequestFingerprintIsNil() predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIsNull(FieldRequestFingerprint))
}

// RequestFingerprintNotNil applies the NotNil predicate on the "request_fingerprint" field.
func RequestFingerprintNotNil() predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotNull(FieldRequestFingerprint))
}

// RequestFingerprintEqualFold applies the EqualFold predicate on the "request_fingerprint" field.
func RequestFingerprintEqualFold(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEqualFold(FieldRequestFingerprint, v))
}

// RequestFingerprintContainsFold applies the ContainsFold predicate on the "request_fingerprint" field.
func RequestFingerprintContainsFold(v string) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldContainsFold(FieldRequestFingerprint, v))
}

// FingerprintKeyVersionEQ applies the EQ predicate on the "fingerprint_key_version" field.
func FingerprintKeyVersionEQ(v int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldFingerprintKeyVersion, v))
}

// FingerprintKeyVersionNEQ applies the NEQ predicate on the "fingerprint_key_version" field.
func FingerprintKeyVersionNEQ(v int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNEQ(FieldFingerprintKeyVersion, v))
}

// FingerprintKeyVersionIn applies the In predicate on the "fingerprint_key_version" field.
func FingerprintKeyVersionIn(vs ...int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIn(FieldFingerprintKeyVersion, vs...))
}

// FingerprintKeyVersionNotIn applies the NotIn predicate on the "fingerprint_key_version" field.
func FingerprintKeyVersionNotIn(vs ...int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotIn(FieldFingerprintKeyVersion, vs...))
}

// FingerprintKeyVersionGT applies the GT predicate on the "fingerprint_key_version" field.
func FingerprintKeyVersionGT(v int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGT(FieldFingerprintKeyVersion, v))
}

// FingerprintKeyVersionGTE applies the GTE predicate on the "fingerprint_key_version" field.
func FingerprintKeyVersionGTE(v int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGTE(FieldFingerprintKeyVersion, v))
}

// FingerprintKeyVersionLT applies the LT predicate on the "fingerprint_key_version" field.
func FingerprintKeyVersionLT(v int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLT(FieldFingerprintKeyVersion, v))
}

// FingerprintKeyVersionLTE applies the LTE predicate on the "fingerprint_key_version" field.
func FingerprintKeyVersionLTE(v int) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLTE(FieldFingerprintKeyVersion, v))
}

// FingerprintSaltEQ applies the EQ predicate on the "fingerprint_salt" field.
func FingerprintSaltEQ(v []byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldFingerprintSalt, v))
}

// FingerprintSaltNEQ applies the NEQ predicate on the "fingerprint_salt" field.
func FingerprintSaltNEQ(v []byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNEQ(FieldFingerprintSalt, v))
}

// FingerprintSaltIn applies the In predicate on the "fingerprint_salt" field.
func FingerprintSaltIn(vs ...[]byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIn(FieldFingerprintSalt, vs...))
}

// FingerprintSaltNotIn applies the NotIn predicate on the "fingerprint_salt" field.
func FingerprintSaltNotIn(vs ...[]byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotIn(FieldFingerprintSalt, vs...))
}

// FingerprintSaltGT applies the GT predicate on the "fingerprint_salt" field.
func FingerprintSaltGT(v []byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGT(FieldFingerprintSalt, v))
}

// FingerprintSaltGTE applies the GTE predicate on the "fingerprint_salt" field.
func FingerprintSaltGTE(v []byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGTE(FieldFingerprintSalt, v))
}

// FingerprintSaltLT applies the LT predicate on the "fingerprint_salt" field.
func FingerprintSaltLT(v []byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLT(FieldFingerprintSalt, v))
}

// FingerprintSaltLTE applies the LTE predicate on the "fingerprint_salt" field.
func FingerprintSaltLTE(v []byte) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLTE(FieldFingerprintSalt, v))
}

// FingerprintSaltIsNil applies the IsNil predicate on the "fingerprint_salt" field.
func FingerprintSaltIsNil() predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIsNull(FieldFingerprintSalt))
}

// FingerprintSaltNotNil applies the NotNil predicate on the "fingerprint_salt" field.
func FingerprintSaltNotNil() predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotNull(FieldFingerprintSalt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestAudit {
	return predicate.RequestAudit(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUsageLog applies the HasEdge predicate on the "usage_log" edge.
func HasUsageLog() predicate.RequestAudit {
	return predicate.RequestAudit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogWith applies the HasEdge predicate on the "usage_log" edge with a given conditions (other predicates).
func HasUsageLogWith(preds ...predicate.UsageLog) predicate.RequestAudit {
	return predicate.RequestAudit(func(s *sql.Selector) {
		step := newUsageLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestAudit) predicate.RequestAudit {
	return predicate.RequestAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestAudit) predicate.RequestAudit {
	return predicate.RequestAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestAudit) predicate.RequestAudit {
	return predicate.RequestAudit(sql.NotPredicates(p))
}
